--connect as admin

--create credential OCI$RESOURCE_PRINCIPAL and grant to users

EXEC DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL();

BEGIN

 DBMS_CLOUD_ADMIN.ENABLE_RESOURCE_PRINCIPAL(username => 'CLOUD_PRACTICALPLSQL');

END;
/

GRANT EXECUTE ON DBMS_CLOUD TO CLOUD_PRACTICALPLSQL;
