
set serveroutput on;
declare
    subtype plLang is json;
    subtype plSqlCode is clob;
    subtype identifier is varchar2(128);
    myDef plLang;
    myCode plsqlCode;
    type pDef is record(
        pName identifier,
        pDirection varchar2(20),
        pType identifier,
        pDefault varchar2(1000)
    );
--    type stDef is record(
--        stName varchar2(128),
--        stType varchar2(128),
--        isNullable boolean);
--    type tDef is record(
--        tName varchar2(128),
--        tType varchar2(128),
--        isArray 
    type pDefs is table of pDef;
    type vDef is record(
        vName identifier,
        isConstant boolean,
        isPublic boolean,
        vType identifier,
        vDefault varchar2(100)
    );
    type vDefs is table of vDef;
    type eDef is record(
        when_condition identifier,
        when_code varchar2(4000));
    type eDefs is table of eDef;
    type methodLines is table of varchar2(1000) index by pls_integer;
    type methodDef is record(
        methodName identifier,
        isFunction boolean,
        isPublic   boolean,
        parameters     pDefs,
        variables       vDefs,
        methodCode methodLines,
        exceptions eDefs
    );
    type methodDefs is table of methodDef;
    
    function pgenMethodSignature(m in methodDef, in_spec in boolean default false) return plsqlcode
    is
        p pDefs := pDefs();
        c plsqlcode;
        lf constant varchar2(1) := chr(10);
        isFunction boolean := false;
        mName identifier;
    begin
    
        mName := m.methodName; 
        isFunction := m.isFunction;
        
        c := case when isFunction then 'function' else 'procedure' end || ' ' || mName;
    
        if m.parameters is not null and m.parameters.count > 0 then
            p := m.parameters; 
        end if;
        
        if (isFunction and p.count > 1) or (not isfunction and p.count > 0) then
            c := c || '(' || lf;
            for i in 1..p.count loop
                if not isFunction or i > 1 then
                    c := c || p(i).pName || ' ' || nvl(p(i).pDirection,'in') || ' ' || p(i).pType 
                    || case when p(i).pDefault is not null then ' default ' || p(i).pdefault end
                    || case when i <> p.count then ',' end || lf;
                end if;
            end loop;
            c := c || ')'; 
        end if;
        c := c || case when isFunction then ' return ' || p(1).pType end;
        
        c := c || case when in_spec then ';' end || lf;
        
        return c;
        
    
    end pgenMethodSignature;
        
    function pgenMethod(m in methodDef) return plsqlcode
    is
        --p pDefs := pDefs();
        v vDefs := vDefs();
        e eDefs := eDefs();
        c plsqlcode;
        lf constant varchar2(1) := chr(10);
        isFunction boolean := false;
        mName identifier;
    begin
        mName := m.methodName; 
        isFunction := m.isFunction;
        
        
        c := pgenMethodSignature(m, false);
        
--        if m.parameters is not null and m.parameters.count > 0 then
--            p := m.parameters; 
--        end if;    
        
        c := c || 'is' || lf;
        if m.variables is not null and m.variables.count > 0 then
            v := m.variables;
            c := c || '--variables defined' || lf;
            for i in 1..v.count loop
                c := c || v(i).vName 
                    || case when v(i).isConstant then ' constant' end 
                    || ' ' || v(i).vType 
                    || case when v(i).vDefault is not null then ' := ' || v(i).vDefault end || ';' || lf;
            end loop;
        end if;
        c := c || 'begin' || lf;
        if m.methodCode.count = 0 then
            c := c || 'null;' || lf;
        else
            for v in values of m.methodCode loop
                c := c || v || lf;
            end loop;
        end if;
--        c := c || m.methodCode || lf; 
        if m.exceptions is not null and m.exceptions.count > 0 then
            e := m.exceptions;
            c := c || '--exceptions defined' || lf;
        end if;
        c := c || 'end ' || mName || ';' || lf;
        
        return c;
        
    
    end pgenMethod;
    
    function pgenPackage(s in plLang) return plsqlcode
    is
        m methodDefs;
        objName identifier;
        objType identifier;
        c plsqlcode;
        lf constant varchar2(10) := chr(10);
        generatedInfo constant varchar2(100) := '--generated by plLang ' || to_char(sysdate,'yyyy-mm-dd hh24:mi:ss') || lf;
    begin
        objName := json_value(s, '$.objectName');
        objType := json_value(s, '$.objectType');
        
        if objType = 'package' then
            c := 'create or replace package ' || objName || lf;
            --authid
            c := c || 'as' || lf;
            c := c || generatedInfo;
            
            c := c || '--public types' || lf;
            c := c || '--public variables' || lf;
            
    
            m := json_value(s, '$.methods' returning methodDefs);
            
            c := c || '--public methods' || lf;
            for i in 1..m.count loop
                if m(i).isPublic then
                    c := c || lf || pgenMethodSignature(m(i), true) || lf;
                end if;
            end loop;
    
            c := c || 'end ' || objName || ';' || lf || '/' || lf;
        
            c := c || 'create or replace package body ' || objName || lf;
            c := c || 'as' || lf;
            c := c || generatedInfo;
            c := c || '--private types' || lf;
            c := c || '--private variables' || lf;
        
            c := c || '--private implementations' || lf;
            for i in 1..m.count loop
                c := c || lf || pgenMethod(m(i)) || lf;
            end loop;        
            
            c := c || '--package initialization' || lf;
            c := c || 'begin' || lf;
            c := c || 'null;' || lf;
            c := c || 'end ' || objName || ';' || lf || '/' || lf;
            
        else
            c := '--not a package';
        end if;
        
        return c;
    
    end pgenPackage;
    
begin

    myDef := 
json(q'~
{
"objectType":"package",
"objectName":"utilMath",
"types":[],
"variables":[{"vName":"cZero","isPublic":true,"isConstant":true,"vType":"number","vDefault":0}],
"methods":
    [
        {
        "methodName":"multiply",
        "isFunction":true,
        "isPublic":true,
        "parameters":
            [
            {"pName":"retVal","pDirection":"return","pType":"number"},
            {"pName":"x","pDirection":"in","pType":"number","pDefault":0},
            {"pName":"y","pDirection":"in","pType":"number","pDefault":0}
            ],
        "variables":
            [
            {"vName":"l_ret","isConstant":false,"vType":"number","vDefault":0},
            {"vName":"l_count","isConstant":true,"vType":"number","vDefault":-1}
            ],
        "methodCode":["return x * y;"],
        "exceptions":[]
        },
        {
        "methodName":"divide",
        "isFunction":true,
        "isPublic":true,
        "parameters":
            [
            {"pName":"retVal","pDirection":"return","pType":"number"},
            {"pName":"x","pDirection":"in","pType":"number","pDefault":0},
            {"pName":"y","pDirection":"in","pType":"number","pDefault":0}
            ],
        "variables":
            [
            {"vName":"l_ret","isConstant":false,"vType":"number","vDefault":0},
            {"vName":"l_count","isConstant":true,"vType":"number","vDefault":-1}
            ],
        "methodCode":[
        "if y = gZero then",
        "raise_application_error(-20100, 'Detected Attempt At Division By Zero');",
        "end if;",
        "return x / y;"
        ],
        "exceptions":[]
        }
    ]
}
~');

    myCode := pgenPackage(mydef);
    
    dbms_output.put_Line(myCode);

end;
/

/*
select
json_query(
json('
{
"objectType":"package",
"objectName":"mathUtil",
"types":[],
"variables":[{"vName":"g_count","isPublic":true,"isConstant":false,"vType":"number","vDefault":0}],
"methods":
    [
        {
        "methodName":"multiply",
        "isFunction":true,
        "isPublic":true,
        "parameters":
            [
            {"pName":"retVal","pDirection":"return","pType":"number"},
            {"pName":"x","pDirection":"in","pType":"number","pDefault":0},
            {"pName":"y","pDirection":"in","pType":"number","pDefault":0}
            ],
        "variables":
            [
            {"vName":"cZero","isConstant":true,"vType":"number","vDefault":0}
            ],
        "methodCode":"return x * y;",
        "exceptions":[]
        }
    ]
}
'),
'$.methods' returning clob pretty)
/

*/