set serveroutput on;
declare
    subtype plLang is json;
    subtype plSqlCode is clob;
    myDef plLang;
    myCode plsqlCode;
    type pDef is record(
        pName varchar2(100),
        pDirection varchar2(20),
        pType varchar2(100),
        parameterDefault varchar2(1000)
    );
    type pDefs is table of pDef;
    type vDef is record(
        vName varchar2(100),
        isPublic boolean,
        vType varchar2(100),
        vDefault varchar2(100)
    );
    type vDefs is table of vDef;
    type eDef is record(
        when_condition varchar2(100),
        when_code varchar2(4000));
    type eDefs is table of eDef;
    type methodDef is record(
        methodName varchar2(100),
        isFunction boolean,
        isPublic   boolean,
        parameters     pDefs,
        variables       vDefs,
        methodCode varchar2(4000),
        exceptions eDefs
    );
    type methodDefs is table of methodDef;
    
    function pgenMethodSignature(m in methodDef, in_spec in boolean default false) return plsqlcode
    is
        p pDefs := pDefs();
        c plsqlcode;
        lf constant varchar2(1) := chr(10);
        isFunction boolean := false;
        mName varchar2(100);
    begin
    
        mName := m.methodName; 
        isFunction := m.isFunction;
        
        c := case when isFunction then 'function' else 'procedure' end || ' ' || mName;
    
        if m.parameters is not null and m.parameters.count > 0 then
            p := m.parameters; 
        end if;
        
        if (isFunction and p.count > 1) or (not isfunction and p.count > 0) then
            c := c || '(' || lf;
            for i in 1..p.count loop
                if not isFunction or i > 1 then
                    c := c || p(i).pName || ' ' || p(i).pDirection || ' ' || p(i).pType || case when i <> p.count then ',' end || lf;
                end if;
            end loop;
            c := c || ')'; 
        end if;
        c := c || case when isFunction then ' return ' || p(1).pType end;
        
        c := c || case when in_spec then ';' end || lf;
        
        return c;
        
    
    end pgenMethodSignature;
        
    function pgenMethod(m in methodDef) return plsqlcode
    is
        --p pDefs := pDefs();
        v vDefs := vDefs();
        e eDefs := eDefs();
        c plsqlcode;
        lf constant varchar2(1) := chr(10);
        isFunction boolean := false;
        mName varchar2(100);
    begin
        mName := m.methodName; 
        isFunction := m.isFunction;
        
        
        c := pgenMethodSignature(m, false);
        
--        if m.parameters is not null and m.parameters.count > 0 then
--            p := m.parameters; 
--        end if;    
        
        c := c || 'is' || lf;
        if m.variables is not null and m.variables.count > 0 then
            v := m.variables;
            c := c || '--variables defined' || lf;
        end if;
        c := c || 'begin' || lf;
        c := c || m.methodCode || lf; 
        if m.exceptions is not null and m.exceptions.count > 0 then
            e := m.exceptions;
            c := c || '--exceptions defined' || lf;
        end if;
        c := c || 'end ' || mName || ';' || lf;
        
        return c;
        
    
    end pgenMethod;
    
    function pgenPackage(s in plLang) return plsqlcode
    is
        m methodDefs;
        objName varchar2(100);
        objType varchar2(100);
        c plsqlcode;
        lf constant varchar2(10) := chr(10);
        generatedInfo constant varchar2(100) := '--generated by plLang ' || to_char(sysdate,'yyyy-mm-dd hh24:mi:ss') || lf;
    begin
        objName := json_value(s, '$.objectName');
        objType := json_value(s, '$.objectType');
        
        if objType = 'package' then
            c := 'create or replace package ' || objName || lf;
            --authid
            c := c || 'as' || lf;
            c := c || generatedInfo;
            
            c := c || '--public types' || lf;
            c := c || '--public variables' || lf;
            
    
            m := json_value(s, '$.methods' returning methodDefs);
            
            c := c || '--public methods' || lf;
            for i in 1..m.count loop
                if m(i).isPublic then
                    c := c || lf || pgenMethodSignature(m(i), true) || lf;
                end if;
            end loop;
    
            c := c || 'end ' || objName || ';' || lf || '/' || lf;
        
            c := c || 'create or replace package body ' || objName || lf;
            c := c || 'as' || lf;
            c := c || generatedInfo;
            c := c || '--private types' || lf;
            c := c || '--private variables' || lf;
        
            c := c || '--private implementations' || lf;
            for i in 1..m.count loop
                c := c || lf || pgenMethod(m(i)) || lf;
            end loop;        
            
            c := c || '--package initialization' || lf;
            c := c || 'begin' || lf;
            c := c || 'null;' || lf;
            c := c || 'end ' || objName || ';' || lf || '/' || lf;
            
        else
            c := '--not a package';
        end if;
        
        return c;
    
    end pgenPackage;
    
begin

    myDef := 
json('
{
"objectType":"package",
"objectName":"my_package",
"types":[],
"variables":[{"vName":"g_count","isPublic":true,"isConstant":false,"vType":"number","vDefault":0}],
"methods":
    [
        {
        "methodName":"test",
        "isFunction":true,
        "isPublic":true,
        "parameters":
            [
            {"pName":"retVal","pDirection":"return","pType":"number"},
            {"pName":"x","pDirection":"in","pType":"number"},
            {"pName":"y","pDirection":"in","pType":"number"}
            ],
        "variables":
            [
            {"vName":"l_ret","isConstant":false,"vType":"number","vDefault":0}
            ],
        "methodCode":"return x * y;",
        "exceptions":[]
        }
    ]
}
');

    myCode := pgenPackage(mydef);
    
    dbms_output.put_Line(myCode);

end;
/

/*
select
json_query(
json('
{
"objectType":"package",
"objectName":"my_package",
"types":[],
"variables":[{"vName":"g_count","isPublic":true,"isConstant":false,"vType":"number","vDefault":0}],
"methods":
    [
        {
        "methodName":"test",
        "isFunction":true,
        "isPublic":true,
        "parameters":
            [
            {"pName":"retVal","pDirection":"return","pType":"number"},
            {"pName":"x","pDirection":"in","pType":"number"},
            {"pName":"y","pDirection":"in","pType":"number"}
            ],
        "variables":
            [
            {"vName":"l_ret","isConstant":false,"vType":"number","vDefault":0}
            ],
        "methodCode":"return x * y;",
        "exceptions":[]
        }
    ]
}
'),
'$.methods' returning clob pretty)
/

*/