prompt loading menu items for category: Breakfast
prompt script generated: 2025-08-17 21:10:29

set feedback on;
set serveroutput on;

declare

    l_count number;
    c menu_categories.category_name%type;

    type t_category_ids is table of integer index by varchar2(100);
    l_categories t_category_ids;

    procedure load_categories_array
    is
    begin
        l_categories := t_category_ids(for r in (select category_name, category_id from menu_categories) index r.category_name => r.category_id);
    end load_categories_array;

     procedure create_item(
        p_category_name in varchar2, 
        p_item_name in varchar2, 
        p_description in varchar2, 
        p_created_by in varchar2 default 'sample')
     is
        l_category_id integer := l_categories(p_category_name);
     begin     
        savepoint new_menu_item;

        insert into menu_items (item_name, category_id, item_description, created_by)
        values (p_item_name, l_category_id, p_description, p_created_by);
    exception
        when others then
            rollback to new_menu_item;
            dbms_output.put_line('Error inserting item: ' || p_item_name || ' SQLERRM: ' || sqlerrm);            
     end create_item;

begin

    load_categories_array;
 

    c := 'Breakfast';
    delete menu_items 
    where category_id = l_categories(c);

    dbms_output.put_line('Deleted ' || sql%rowcount || ' existing menu items for category: ' || c);

 


create_item(c, q'~Australian Vegemite Toast~', q'~Buttered sourdough toast spread with savory Vegemite and topped with creamy sliced avocado. A beloved Australian breakfast staple, often enjoyed with a sprinkle of grated cheddar cheese and a side of fresh fruit.~');
create_item(c, q'~Avocado Toast~', q'~Toasted artisan sourdough bread topped with creamy, freshly smashed ripe avocado, finished with a sprinkle of flaky sea salt and cracked black pepper. Garnished with thinly sliced radishes, microgreens, and a drizzle of extra virgin olive oil. Optional toppings include a perfectly poached egg, juicy heirloom tomato slices, or crumbled feta cheese for added richness and flavor. Served open-faced and accompanied by a wedge of lemon for a bright, refreshing breakfast experience.~');
create_item(c, q'~Bagel with Cream Cheese~', q'~A freshly toasted bagel, crisp on the outside and chewy inside, generously spread with smooth, tangy cream cheese. Often served plain or with toppings like smoked salmon, capers, or sliced tomatoes for a classic breakfast treat. Accompanied by a side of fresh fruit or a light salad for a balanced meal.~');
create_item(c, q'~Belgian Liege Waffle~', q'~Rich, chewy waffle made with pearl sugar, caramelized on the outside and soft within. Served warm with whipped cream, fresh berries, and a drizzle of chocolate sauce for a decadent Belgian breakfast treat.~');
create_item(c, q'~Brazilian Pão de Queijo~', q'~Warm, chewy cheese bread balls made from tapioca flour and aged Parmesan cheese. Naturally gluten-free and perfect for breakfast or snacking, these Brazilian treats are served fresh from the oven and often enjoyed with a cup of strong coffee.~');
create_item(c, q'~Breakfast Burrito~', q'~A large flour tortilla filled with fluffy scrambled eggs, melted cheddar cheese, savory sausage or crispy bacon, golden hash brown potatoes, and zesty salsa. Rolled up and grilled for a warm, hearty breakfast. Served with a side of guacamole and pico de gallo for extra flavor.~');
create_item(c, q'~Breakfast Sandwich~', q'~A hearty morning sandwich featuring a freshly cooked egg, gooey melted cheese, and crispy bacon layered on a toasted English muffin or buttery croissant. Served hot and perfect for a grab-and-go breakfast, with optional additions like sliced tomato, avocado, or spinach for extra nutrition.~');
create_item(c, q'~Chinese Jianbing~', q'~Savory Chinese crepe made with mung bean and wheat flour, layered with a fresh egg, scallions, cilantro, crispy wonton crackers, and sweet hoisin sauce. Rolled and served hot, often enjoyed as a street food breakfast in China. Customizable with chili paste or pickled vegetables for extra flavor.~');
create_item(c, q'~Colombian Arepa de Huevo~', q'~Cornmeal cake stuffed with a whole egg and deep-fried until crispy and golden. Served with tangy ají sauce and a side of fresh fruit for a Colombian breakfast specialty.~');
create_item(c, q'~Costa Rican Gallo Pinto~', q'~Savory mix of rice and black beans sautéed with onions, bell peppers, and fresh cilantro. Served with fried eggs, crispy plantains, and a side of sour cream for a traditional Costa Rican breakfast plate.~');
create_item(c, q'~Cuban Tostada con Café~', q'~Buttered Cuban bread pressed and toasted until crisp, served with a shot of sweet café con leche. Often enjoyed with a side of fresh tropical fruit for a classic Cuban breakfast.~');
create_item(c, q'~Danish Smørrebrød with Egg~', q'~Open-faced rye bread sandwich topped with sliced boiled eggs, pickled herring, fresh dill, and tangy mustard sauce. Served with a side of crisp cucumber salad for a traditional Danish breakfast.~');
create_item(c, q'~Eggs Benedict~', q'~Poached eggs and Canadian bacon layered on toasted English muffin halves, topped with rich, velvety hollandaise sauce. Served with breakfast potatoes and a garnish of fresh chives or parsley. A classic brunch dish known for its creamy, savory flavors and elegant presentation.~');
create_item(c, q'~Egyptian Ful Medames~', q'~Slow-cooked fava beans seasoned with garlic, lemon juice, olive oil, and earthy cumin. Garnished with chopped parsley, diced tomatoes, and sliced hard-boiled eggs, and served with warm pita bread for a nutritious, protein-rich breakfast.~');
create_item(c, q'~Ethiopian Firfir~', q'~Shredded injera, a spongy Ethiopian flatbread, tossed with spicy berbere sauce, sautéed onions, and ripe tomatoes. Served warm and garnished with fresh herbs, offering a hearty, flavorful breakfast with a unique tangy and spicy profile.~');
create_item(c, q'~Filipino Tapsilog~', q'~Garlic fried rice, tender marinated beef tapa, and a sunny-side-up egg, served with pickled papaya (atchara) and sliced tomatoes. A hearty Filipino breakfast plate that balances savory, sweet, and tangy flavors for a satisfying start to the day.~');
create_item(c, q'~Finnish Karjalanpiirakka~', q'~Traditional rye pastry filled with creamy rice porridge, topped with a generous dollop of egg butter. Served warm and often accompanied by slices of cheese and fresh cucumber for a Finnish breakfast treat.~');
create_item(c, q'~French Croque Madame~', q'~Grilled ham and Gruyère cheese sandwich topped with creamy béchamel sauce and a perfectly fried egg. Served hot for a decadent French breakfast, often accompanied by a light salad or crispy potatoes.~');
create_item(c, q'~French Toast~', q'~Slices of thick-cut bread soaked in a cinnamon-vanilla egg mixture, pan-fried until golden brown and slightly crisp. Served with a dusting of powdered sugar, a drizzle of warm maple syrup, and a medley of fresh berries. Optional toppings include whipped cream, toasted nuts, or caramelized bananas for a decadent breakfast.~');
create_item(c, q'~German Bauernfrühstück~', q'~Hearty farmer’s breakfast of sautéed potatoes, sweet onions, crispy bacon, and scrambled eggs, finished with fresh parsley and chives. Served hot and often accompanied by slices of rustic bread and pickled vegetables.~');
create_item(c, q'~Gluten-Free Almond Flour Pancakes~', q'~Fluffy pancakes made with almond flour, served warm with fresh berries and pure maple syrup. Perfect for gluten-sensitive guests, these pancakes are light, nutty, and satisfying.~');
create_item(c, q'~Gluten-Free Buckwheat Crepes~', q'~Thin, delicate buckwheat crepes filled with sautéed spinach, tangy goat cheese, and roasted red peppers. Each crepe is cooked to a golden finish, then rolled and served with a crisp side salad of mixed greens, cherry tomatoes, and a drizzle of balsamic glaze. The gluten-free batter yields a nutty flavor and tender texture, making this breakfast both wholesome and satisfying. Garnished with fresh herbs and a sprinkle of cracked black pepper for a vibrant morning meal.~');
create_item(c, q'~Gluten-Free Sweet Potato Hash~', q'~Roasted sweet potatoes tossed with tender kale, caramelized red onions, and hearty black beans, topped with a perfectly poached egg. Served with a side of fresh salsa for a gluten-free breakfast option.~');
create_item(c, q'~Greek Spanakopita Omelette~', q'~Fluffy omelette filled with sautéed spinach, tangy feta cheese, fresh dill, and scallions. Inspired by the classic Greek pastry, this breakfast dish is served hot and garnished with lemon wedges and olives for a Mediterranean touch.~');
create_item(c, q'~Hawaiian Loco Moco~', q'~Steamed rice topped with a juicy hamburger patty, a perfectly fried egg, and rich brown gravy. Served with a side of macaroni salad and fresh pineapple for a comforting Hawaiian breakfast bowl.~');
create_item(c, q'~Huevos Rancheros~', q'~A traditional Mexican breakfast dish featuring sunny-side-up eggs served on lightly fried corn tortillas, topped with a savory tomato-chili ranchero sauce, creamy refried beans, sliced avocado, and crumbled queso fresco. Garnished with fresh cilantro and accompanied by a side of Mexican rice for a flavorful, satisfying meal.~');
create_item(c, q'~Hungarian Lángos~', q'~Golden fried yeast dough topped with garlic oil, tangy sour cream, and shredded cheese. A popular Hungarian breakfast street food, served hot and often enjoyed with smoked meats or fresh vegetables.~');
create_item(c, q'~Indian Masala Dosa~', q'~A crispy, golden fermented rice and lentil crepe filled with spicy potato masala, seasoned with mustard seeds, curry leaves, and turmeric. Served with cooling coconut chutney and tangy sambar for dipping. A South Indian breakfast classic, both gluten-free and vegetarian.~');
create_item(c, q'~Indonesian Bubur Ayam~', q'~Chicken rice porridge garnished with crispy fried shallots, sliced scallions, roasted peanuts, and crunchy crackers. Served with sweet soy sauce and spicy chili paste for a comforting Indonesian breakfast bowl.~');
create_item(c, q'~Iranian Kuku Sabzi~', q'~Herb-packed Persian frittata made with parsley, cilantro, dill, scallions, and crunchy walnuts. Baked until set and sliced into wedges, served with flatbread and yogurt for a nutritious Iranian breakfast.~');
create_item(c, q'~Irish Boxty~', q'~Crispy potato pancake made with a blend of grated and mashed potatoes, pan-fried until golden brown. Served with smoked salmon, chive sour cream, and a side of sautéed greens for a classic Irish breakfast experience.~');
create_item(c, q'~Israeli Shakshuka with Feta~', q'~Eggs poached in a spicy tomato and bell pepper sauce, topped with crumbled feta cheese and fresh parsley. Served with warm pita bread for dipping into the rich, flavorful sauce. A Mediterranean breakfast favorite, both vegetarian and protein-rich.~');
create_item(c, q'~Italian Frittata di Verdure~', q'~Open-faced omelette loaded with seasonal vegetables, aromatic fresh herbs, and grated Parmesan cheese. Baked until golden and sliced into wedges, served warm with a side of mixed greens for a classic Italian breakfast.~');
create_item(c, q'~Jamaican Ackee and Saltfish~', q'~Ackee fruit sautéed with salted cod, onions, tomatoes, and fiery Scotch bonnet peppers. Served with crispy fried dumplings, sweet plantains, and a side of callaloo for a vibrant, flavorful Jamaican breakfast plate.~');
create_item(c, q'~Japanese Tamago Sando~', q'~Fluffy Japanese egg salad made with creamy Kewpie mayonnaise, finely chopped eggs, and a touch of white pepper, sandwiched between pillowy slices of milk bread. Served chilled and cut into neat rectangles for a delicate, satisfying breakfast or snack. Often enjoyed with a side of pickled vegetables.~');
create_item(c, q'~Korean Gyeran Bap~', q'~Steamed short-grain rice topped with a perfectly fried egg, a splash of soy sauce, toasted sesame oil, and chopped scallions. Comforting and simple, this Korean breakfast bowl is often garnished with roasted seaweed and sesame seeds for added flavor and texture.~');
create_item(c, q'~Lebanese Manakish Za’atar~', q'~Soft, pillowy flatbread topped with a fragrant blend of za’atar herbs, olive oil, and toasted sesame seeds. Baked fresh and served warm, often accompanied by sliced tomatoes, cucumbers, and olives for a traditional Lebanese breakfast spread.~');
create_item(c, q'~Low-Carb Cauliflower Breakfast Bowl~', q'~Riced cauliflower sautéed with lean turkey sausage, fresh spinach, and sweet cherry tomatoes, finished with a soft-boiled egg. Garnished with sliced avocado and fresh herbs for a nutritious, low-carb breakfast.~');
create_item(c, q'~Malaysian Nasi Lemak~', q'~Fragrant coconut rice served with spicy sambal, crispy fried anchovies, roasted peanuts, fresh cucumber slices, and a hard-boiled egg. Accompanied by tender chicken or beef rendang for a complete Malaysian breakfast experience.~');
create_item(c, q'~Mexican Chilaquiles Verdes~', q'~Crispy tortilla chips simmered in tangy tomatillo salsa, topped with fried eggs, crumbled queso fresco, creamy Mexican crema, and fresh cilantro. Served with refried beans and avocado slices for a vibrant, satisfying breakfast plate.~');
create_item(c, q'~Moroccan Msemen~', q'~Flaky, pan-fried semolina flatbread brushed with golden honey and melted butter, often enjoyed with a steaming cup of mint tea for a traditional Moroccan breakfast. Served warm and sometimes accompanied by soft cheese or fruit preserves for a sweet and savory experience.~');
create_item(c, q'~Nepalese Sel Roti~', q'~Crispy, ring-shaped rice flour doughnut, lightly sweetened and fried until golden brown. Served with spiced potato curry and a cup of hot chai for a traditional Nepalese breakfast.~');
create_item(c, q'~Omelette~', q'~A fluffy, three-egg omelette cooked to order and filled with your choice of ingredients such as sharp cheddar cheese, diced ham, sautéed mushrooms, fresh spinach, juicy tomatoes, and aromatic herbs. Served hot with a side of buttered toast or a crisp garden salad. Customizable for vegetarian or meat lovers alike.~');
create_item(c, q'~Pakistani Anda Paratha~', q'~Flaky whole wheat paratha stuffed with spiced scrambled eggs, seasoned with green chilies, onions, and fresh coriander. Served hot with creamy yogurt and tangy pickles for a traditional Pakistani breakfast.~');
create_item(c, q'~Pancakes~', q'~A stack of light and fluffy pancakes made from scratch, served piping hot with a pat of creamy butter and a generous pour of warm maple syrup. Optionally topped with fresh seasonal fruit, whipped cream, or crunchy toasted nuts for added texture and sweetness. Perfect for a comforting breakfast or brunch.~');
create_item(c, q'~Persian Barbari Bread with Feta~', q'~Thick, chewy Persian flatbread topped with toasted sesame seeds, served with creamy feta cheese, fresh herbs, and sliced cucumber. Accompanied by olives and tomatoes for a classic Persian breakfast spread.~');
create_item(c, q'~Peruvian Tamal Verde~', q'~Steamed corn dough blended with fragrant cilantro and filled with tender chicken or creamy cheese, wrapped in banana leaves and served with tangy salsa criolla. A traditional Peruvian breakfast, both savory and aromatic.~');
create_item(c, q'~Polish Jajecznica~', q'~Scrambled eggs cooked with caramelized onions and smoky kielbasa sausage, served with slices of hearty rye bread. A traditional Polish breakfast, often enjoyed with pickled cucumbers and fresh herbs for extra flavor.~');
create_item(c, q'~Puerto Rican Mallorca~', q'~Sweet, fluffy spiral bun dusted with powdered sugar, sliced and filled with savory ham and melted cheese. Grilled and served warm, often enjoyed with a cup of café con leche for a Puerto Rican breakfast treat.~');
create_item(c, q'~Russian Syrniki~', q'~Golden-fried farmer’s cheese pancakes, lightly sweetened and served with a dollop of tangy sour cream and homemade berry preserves. A classic Eastern European breakfast treat, often enjoyed with a dusting of powdered sugar and fresh mint.~');
create_item(c, q'~Scottish Porridge with Whisky Cream~', q'~Creamy steel-cut oats simmered in milk, topped with whisky-infused whipped cream and toasted oats. Garnished with fresh berries and a drizzle of honey for a luxurious Scottish breakfast.~');
create_item(c, q'~Shakshuka~', q'~A North African and Middle Eastern breakfast of eggs poached in a spicy, aromatic tomato and bell pepper sauce, seasoned with cumin, paprika, and garlic. Served hot in a cast iron skillet, garnished with fresh parsley and crumbled feta cheese. Accompanied by crusty bread for dipping into the rich, flavorful sauce.~');
create_item(c, q'~Singaporean Kaya Toast~', q'~Crispy toast spread with sweet coconut jam (kaya) and cold butter, served with soft-boiled eggs and a splash of dark soy sauce. Accompanied by a cup of strong local coffee for a classic Singaporean breakfast.~');
create_item(c, q'~South African Mealie Pap~', q'~Creamy maize porridge served with a savory tomato and onion gravy, often enjoyed with grilled sausages or fried eggs. A traditional South African breakfast, hearty and comforting, perfect for fueling a busy day.~');
create_item(c, q'~Spanish Pan con Tomate~', q'~Toasted rustic bread rubbed with ripe tomato, drizzled with extra virgin olive oil, and sprinkled with flaky sea salt. A simple yet flavorful Catalan breakfast, often served with thin slices of cured ham or Manchego cheese for added richness.~');
create_item(c, q'~Swedish Gravlax Toast~', q'~Hearty rye bread topped with house-cured salmon, fresh dill, tangy mustard sauce, and thinly sliced cucumber. Served open-faced and garnished with lemon wedges for a Scandinavian breakfast classic, perfect with a side of pickled vegetables.~');
create_item(c, q'~Syrian Muhammara Toast~', q'~Toasted bread topped with spicy walnut and roasted red pepper spread, finished with olive oil and a sprinkle of pomegranate seeds. Served with sliced cucumbers and tomatoes for a flavorful Syrian breakfast.~');
create_item(c, q'~Thai Jok~', q'~Silky rice porridge simmered with fresh ginger and garlic, topped with seasoned ground pork, sliced scallions, crispy fried shallots, and a soft-boiled egg. Served with a splash of soy sauce and a sprinkle of white pepper for a comforting Thai breakfast bowl.~');
create_item(c, q'~Tofu Scramble~', q'~Crumbled tofu sautéed with golden turmeric, sweet onions, colorful bell peppers, and tender spinach, mimicking the texture and flavor of scrambled eggs. Served hot with toasted whole grain bread or crispy breakfast potatoes. A protein-packed, vegan alternative to traditional egg dishes.~');
create_item(c, q'~Tofu and Spinach Quiche~', q'~A savory, eggless quiche made with blended silken tofu, sautéed spinach, caramelized onions, and aromatic herbs, all nestled in a flaky pastry crust. Baked until golden and set, then sliced and served warm. Perfect for a light, plant-based breakfast or brunch.~');
create_item(c, q'~Tofu and Tomato Shakshuka~', q'~A North African-inspired breakfast featuring tender tofu cubes simmered in a spicy tomato and bell pepper sauce, seasoned with cumin, paprika, and garlic. Garnished with fresh cilantro and served with warm, crusty bread for dipping. A hearty, vegan twist on a classic dish.~');
create_item(c, q'~Tunisian Brik~', q'~Crispy pastry filled with a whole egg, tuna, briny capers, and fresh parsley, deep-fried until golden brown. Served with lemon wedges and a side of spicy harissa for a flavorful Tunisian breakfast.~');
create_item(c, q'~Turkish Menemen~', q'~Scrambled eggs gently cooked with juicy tomatoes, green peppers, sweet onions, and a blend of Mediterranean spices in rich olive oil. Served hot in a skillet, garnished with fresh parsley, and accompanied by crusty bread for dipping. A vibrant, flavorful Turkish breakfast staple.~');
create_item(c, q'~Ukrainian Deruny~', q'~Potato pancakes seasoned with garlic and fresh dill, pan-fried until crisp and golden. Served with tangy sour cream and smoked salmon for a hearty Ukrainian breakfast.~');
create_item(c, q'~Vegan Almond Butter ~' || chr(38) || q'~ Berry Toast~', q'~Whole grain toast generously spread with creamy almond butter and topped with fresh mixed berries. Finished with a drizzle of agave syrup and a sprinkle of chia seeds, this nutritious vegan breakfast or snack is both energizing and satisfying.~');
create_item(c, q'~Vegan Apple Cinnamon Breakfast Bars~', q'~Soft-baked bars made with hearty oats, sweet apples, fragrant cinnamon, and creamy almond butter. Dairy-free and gluten-free, perfect for a quick vegan breakfast or snack.~');
create_item(c, q'~Vegan Apple Cinnamon Breakfast Muffins~', q'~Moist muffins made with apples, cinnamon, and whole wheat flour. Egg-free and dairy-free.~');
create_item(c, q'~Vegan Apple Cinnamon Oatmeal~', q'~Steel-cut oats simmered with sweet diced apples, fragrant cinnamon, plump golden raisins, and creamy almond milk. Topped with toasted walnuts, a drizzle of pure maple syrup, and a sprinkle of chia seeds for added nutrition. Served piping hot in a rustic bowl, this comforting vegan breakfast is both hearty and wholesome, perfect for chilly mornings.~');
create_item(c, q'~Vegan Apple Pie Breakfast Quinoa~', q'~Quinoa simmered with sweet diced apples, fragrant cinnamon, nutmeg, and pure maple syrup. Topped with toasted pecans, dried cranberries, and a dollop of coconut yogurt. Served warm in a rustic bowl, this comforting vegan breakfast offers all the flavors of classic apple pie in a nourishing, protein-packed form.~');
create_item(c, q'~Vegan Avocado Toast with Radish~', q'~Sourdough toast topped with creamy smashed avocado, crisp sliced radishes, nutty hemp seeds, and vibrant microgreens. Finished with a drizzle of cold-pressed olive oil and a sprinkle of sea salt and cracked black pepper. Served open-faced with a wedge of lemon and a side of fresh fruit, this plant-based breakfast is both nourishing and visually appealing.~');
create_item(c, q'~Vegan Banana Nut Breakfast Bars~', q'~Soft-baked bars made with ripe bananas, crunchy walnuts, and hearty oats. Dairy-free and gluten-free, perfect for a quick vegan breakfast or snack.~');
create_item(c, q'~Vegan Banana Nut Breakfast Muffins~', q'~Moist muffins made with ripe bananas, crunchy walnuts, and whole wheat flour. Egg-free and dairy-free, perfect for a plant-based breakfast or snack.~');
create_item(c, q'~Vegan Banana Nut Muffin~', q'~Moist muffin made with ripe bananas, walnuts, and whole wheat flour. Egg-free and dairy-free for a plant-based breakfast.~');
create_item(c, q'~Vegan Berry Chia Jam Toast~', q'~Multigrain toast spread with homemade berry chia jam and creamy almond butter. Finished with a sprinkle of hemp seeds and a side of sliced kiwi and orange. Served open-faced, this nutritious vegan breakfast or snack is packed with antioxidants and healthy fats.~');
create_item(c, q'~Vegan Blueberry Lemon Scones~', q'~Tender, golden scones crafted with coconut oil and almond milk, bursting with juicy blueberries and fragrant lemon zest. Each scone is lightly sweetened and baked to a delicate crumb, offering a moist interior and crisp edges. Finished with a drizzle of tangy lemon glaze and a sprinkle of coarse sugar, these scones are egg-free and dairy-free, making them a perfect choice for a wholesome, plant-based breakfast or afternoon treat. Served warm, they pair beautifully with herbal tea or fresh fruit preserves for a delightful morning indulgence.~');
create_item(c, q'~Vegan Carrot Cake Oatmeal~', q'~Rolled oats cooked with shredded carrots, plump golden raisins, fragrant cinnamon, and crunchy walnuts. Finished with a dollop of coconut yogurt and a sprinkle of toasted coconut flakes. Served hot in a rustic bowl, this wholesome vegan breakfast captures the flavors of classic carrot cake in a nourishing form.~');
create_item(c, q'~Vegan Chickpea Omelette~', q'~Savory chickpea flour batter cooked with fresh spinach, juicy tomatoes, and sweet onions, folded and served with zesty avocado salsa. A protein-rich, vegan alternative to traditional omelettes.~');
create_item(c, q'~Vegan Chocolate Banana Overnight Oats~', q'~Rolled oats soaked overnight in creamy almond milk with rich cocoa, ripe banana slices, and crunchy chia seeds. Served chilled and topped with toasted coconut flakes and cacao nibs for a decadent vegan breakfast. Perfect for meal prep and busy mornings.~');
create_item(c, q'~Vegan Chocolate Chip Breakfast Muffins~', q'~Moist muffins made with creamy coconut oil and vegan chocolate chips. Egg-free and dairy-free, perfect for a wholesome vegan breakfast or snack.~');
create_item(c, q'~Vegan Chocolate Hazelnut Breakfast Bars~', q'~Soft-baked bars made with hearty oats, rich cocoa, toasted hazelnuts, and creamy coconut oil. Dairy-free and gluten-free, perfect for a quick vegan breakfast or snack.~');
create_item(c, q'~Vegan Chocolate Hazelnut Breakfast Muffins~', q'~Moist muffins made with rich cocoa, toasted hazelnuts, and creamy coconut oil. Egg-free and dairy-free, perfect for a decadent vegan breakfast or snack.~');
create_item(c, q'~Vegan Chocolate Hazelnut Granola~', q'~Crunchy granola made with hearty rolled oats, rich cocoa powder, toasted hazelnuts, and coconut oil. Each batch is baked until crisp and fragrant, then served with almond milk or creamy coconut yogurt. Finished with a sprinkle of cacao nibs and dried cherries, this decadent vegan breakfast is both satisfying and energizing.~');
create_item(c, q'~Vegan Cinnamon Raisin Bagel~', q'~Chewy bagel made with whole wheat flour, fragrant cinnamon, and plump raisins. Served toasted with vegan cream cheese, a side of fresh fruit, and a sprinkle of chopped walnuts. This wholesome vegan breakfast is both comforting and satisfying, perfect for a leisurely morning.~');
create_item(c, q'~Vegan Coconut Chia Pudding~', q'~Creamy coconut milk chia pudding topped with mango, toasted coconut flakes, and fresh mint. Served chilled for a refreshing, plant-based breakfast or snack.~');
create_item(c, q'~Vegan Coconut Mango Rice Pudding~', q'~Creamy coconut milk rice pudding layered with juicy fresh mango, toasted coconut flakes, and zesty lime. Served chilled in a glass jar and garnished with mint leaves and a sprinkle of chia seeds. This tropical vegan breakfast treat is both refreshing and satisfying.~');
create_item(c, q'~Vegan Lemon Blueberry Breakfast Muffins~', q'~Moist muffins made with creamy almond milk, zesty lemon, and juicy blueberries. Egg-free and dairy-free, perfect for a light vegan breakfast or snack.~');
create_item(c, q'~Vegan Lemon Poppy Seed Muffins~', q'~Moist muffins made with creamy almond milk, zesty lemon, and crunchy poppy seeds. Each muffin is egg-free and dairy-free, baked until golden, and finished with a sweet lemon glaze. Served warm with a side of fresh fruit, these vegan muffins are perfect for a light breakfast or snack.~');
create_item(c, q'~Vegan Mango Coconut Smoothie Bowl~', q'~A vibrant smoothie bowl blended with ripe mango, sweet banana, and creamy coconut milk. Topped with chia seeds, crunchy homemade granola, toasted coconut flakes, and fresh berries. Served chilled and garnished with mint leaves and a sprinkle of chia seeds, this refreshing vegan breakfast bowl is both tropical and nutrient-rich, perfect for a sunny morning.~');
create_item(c, q'~Vegan Maple Walnut Granola~', q'~Crunchy granola made with hearty oats, pure maple syrup, toasted walnuts, and pumpkin seeds. Each batch is baked until crisp and fragrant, then served with almond milk or creamy coconut yogurt. Finished with dried cranberries and a sprinkle of cinnamon, this wholesome vegan breakfast is both energizing and delicious.~');
create_item(c, q'~Vegan Peanut Butter Banana Toast~', q'~Whole grain toast generously spread with creamy peanut butter, topped with sliced ripe bananas and crunchy chia seeds. Finished with a drizzle of agave syrup and a sprinkle of cinnamon. Served open-faced with a side of fresh berries, this protein-rich vegan breakfast is both energizing and satisfying.~');
create_item(c, q'~Vegan Pumpkin Cranberry Breakfast Muffins~', q'~Moist muffins made with pumpkin puree, tart dried cranberries, and whole wheat flour. Egg-free and dairy-free, perfect for a seasonal vegan breakfast or snack.~');
create_item(c, q'~Vegan Pumpkin Spice Breakfast Muffins~', q'~Moist muffins made with oats, pumpkin puree, fragrant cinnamon, and nutmeg. Egg-free and dairy-free, perfect for a seasonal vegan breakfast or snack.~');
create_item(c, q'~Vegan Pumpkin Spice Overnight Oats~', q'~Rolled oats soaked overnight in creamy almond milk with pumpkin puree, fragrant cinnamon, nutmeg, and pure maple syrup. Served chilled and topped with toasted pecans, dried cranberries, and a sprinkle of pumpkin seeds for added crunch. This seasonal vegan breakfast is both convenient and flavorful, offering a festive twist on classic oats.~');
create_item(c, q'~Vegan Strawberry Almond Breakfast Bars~', q'~Soft-baked bars made with hearty oats, creamy almond butter, sweet strawberries, and ground flaxseed. Each bar is dairy-free and gluten-free, baked until golden, and finished with a drizzle of almond glaze. Perfect for a quick vegan breakfast or snack, these bars are both wholesome and delicious.~');
create_item(c, q'~Vegan Sweet Potato Breakfast Burrito~', q'~A hearty whole wheat tortilla stuffed with oven-roasted sweet potatoes, hearty black beans, creamy avocado slices, and spicy homemade salsa. The filling is seasoned with cumin and smoked paprika, then wrapped and grilled for a warm, satisfying bite. Served with a side of fresh fruit salad and a wedge of lime, this vegan breakfast burrito offers a balance of sweet, savory, and spicy flavors, perfect for a nourishing start to the day.~');
create_item(c, q'~Vegan Tofu Breakfast Tacos~', q'~Soft corn tortillas filled with seasoned scrambled tofu, sautéed bell peppers, sweet onions, and zesty avocado salsa. Each taco is topped with fresh cilantro, sliced radishes, and a squeeze of lime. Served with a side of smoky black beans and a tangy tomato salsa, these dairy-free and gluten-free tacos offer a vibrant, protein-packed vegan breakfast bursting with flavor and color.~');
create_item(c, q'~Vegetarian Asparagus ~' || chr(38) || q'~ Goat Cheese Tart~', q'~Flaky puff pastry topped with roasted asparagus spears, creamy goat cheese, and fresh thyme. Baked until golden and served warm with a side of arugula salad dressed in lemon vinaigrette. The combination of crisp pastry and savory filling makes this tart a sophisticated vegetarian breakfast option.~');
create_item(c, q'~Vegetarian Broccoli ~' || chr(38) || q'~ Cheddar Breakfast Muffin~', q'~Savory muffins packed with steamed broccoli florets, sharp aged cheddar cheese, and sliced scallions. Each muffin is baked to a golden finish and served warm for a grab-and-go breakfast or snack. The tender crumb and cheesy flavor make these muffins a wholesome and convenient morning option.~');
create_item(c, q'~Vegetarian Broccoli ~' || chr(38) || q'~ Cheddar Breakfast Pizza~', q'~Crispy flatbread topped with scrambled eggs, steamed broccoli, sharp cheddar cheese, and sliced scallions. Baked until golden and served warm for a unique vegetarian breakfast.~');
create_item(c, q'~Vegetarian Broccoli ~' || chr(38) || q'~ Cheddar Quiche~', q'~A flaky pastry crust filled with fluffy eggs, steamed broccoli florets, and sharp aged cheddar cheese. Baked until set and golden, then sliced and served warm with a side of mixed greens and cherry tomatoes. This classic vegetarian breakfast is both comforting and delicious.~');
create_item(c, q'~Vegetarian Caprese Breakfast Sandwich~', q'~A toasted ciabatta roll layered with creamy fresh mozzarella, thick slices of ripe tomatoes, aromatic basil pesto, and a perfectly fried farm egg. Garnished with baby arugula and a drizzle of extra virgin olive oil, this Italian-inspired breakfast sandwich is served warm and accompanied by a side of crisp mixed greens. The combination of flavors and textures creates a memorable, savory breakfast experience.~');
create_item(c, q'~Vegetarian Cheddar ~' || chr(38) || q'~ Chive Biscuits~', q'~Flaky buttermilk biscuits loaded with sharp aged cheddar cheese and freshly chopped chives. Each biscuit is baked until golden brown, then served warm with whipped butter and a side of homemade fruit preserves. The savory richness of the cheese and aromatic chives is complemented by the tender crumb, making these biscuits a standout breakfast treat for any occasion.~');
create_item(c, q'~Vegetarian Greek Yogurt Parfait~', q'~Creamy Greek yogurt layered in a tall glass with golden honey, crunchy homemade granola, fresh seasonal berries, and toasted almonds. Each layer is carefully assembled for a beautiful presentation, and the parfait is finished with a sprig of mint and a dusting of cinnamon. Served chilled, this protein-packed breakfast is both refreshing and energizing, perfect for a light morning meal or snack.~');
create_item(c, q'~Vegetarian Mediterranean Breakfast Bowl~', q'~A protein-rich bowl featuring fluffy quinoa topped with roasted chickpeas, crisp cucumber slices, juicy cherry tomatoes, Kalamata olives, and creamy feta cheese. Finished with a tangy lemon-tahini dressing and garnished with fresh parsley and mint. Served with warm pita wedges and a side of marinated artichoke hearts, this Mediterranean-inspired breakfast is both refreshing and filling, ideal for a vibrant morning meal.~');
create_item(c, q'~Vegetarian Mushroom ~' || chr(38) || q'~ Gruyère Crepes~', q'~Thin, tender crepes filled with sautéed mushrooms, nutty Gruyère cheese, and fresh thyme. Each crepe is folded and served with a crisp side salad of mixed greens and cherry tomatoes. The savory filling and delicate crepe make this vegetarian breakfast both elegant and satisfying.~');
create_item(c, q'~Vegetarian Mushroom ~' || chr(38) || q'~ Spinach Strata~', q'~Savory breakfast casserole layered with sourdough bread, sautéed mushrooms, spinach, eggs, and Gruyère cheese. Baked until golden and served warm, perfect for brunch gatherings.~');
create_item(c, q'~Vegetarian Ricotta ~' || chr(38) || q'~ Spinach Stuffed Croissant~', q'~Buttery croissant filled with creamy ricotta cheese, sautéed spinach, and fresh herbs. Baked until golden and flaky, then served warm with a side of mixed greens and cherry tomatoes. The rich filling and crisp pastry make this vegetarian breakfast a decadent morning indulgence.~');
create_item(c, q'~Vegetarian Roasted Red Pepper ~' || chr(38) || q'~ Feta Omelette~', q'~A fluffy omelette filled with roasted red peppers, crumbled feta cheese, and fresh parsley. Cooked to perfection and served hot with a side of mixed greens tossed in lemon vinaigrette. The savory flavors and creamy texture make this vegetarian breakfast a flavorful way to start the day.~');
create_item(c, q'~Vegetarian Roasted Red Pepper ~' || chr(38) || q'~ Spinach Breakfast Muffin~', q'~Savory muffin packed with roasted red peppers, sautéed spinach, and feta cheese.~');
create_item(c, q'~Vegetarian Roasted Red Pepper ~' || chr(38) || q'~ Spinach Breakfast Pizza~', q'~Crispy flatbread topped with scrambled eggs, roasted red peppers, sautéed spinach, and tangy feta cheese. Baked until golden and served warm for a unique vegetarian breakfast.~');
create_item(c, q'~Vegetarian Roasted Sweet Potato Hash~', q'~Oven-roasted sweet potatoes, colorful bell peppers, caramelized onions, and tender spinach, all tossed together and topped with a perfectly fried farm egg. Served with a side of spicy salsa and fresh avocado slices, this hearty vegetarian breakfast is both filling and flavorful.~');
create_item(c, q'~Vegetarian Roasted Tomato ~' || chr(38) || q'~ Basil Breakfast Muffin~', q'~Savory muffin packed with roasted tomatoes, fresh basil leaves, and creamy mozzarella cheese. Served warm for a grab-and-go vegetarian breakfast.~');
create_item(c, q'~Vegetarian Roasted Tomato ~' || chr(38) || q'~ Mozzarella Strata~', q'~Savory breakfast casserole layered with oven-roasted tomatoes, creamy mozzarella cheese, fluffy eggs, and fresh basil. Baked until golden and served warm with a side of arugula salad and balsamic reduction. This comforting vegetarian breakfast is perfect for brunch gatherings.~');
create_item(c, q'~Vegetarian Roasted Vegetable Breakfast Muffin~', q'~Savory muffin packed with roasted zucchini, sweet bell peppers, caramelized onions, and sharp cheddar cheese. Served warm for a grab-and-go vegetarian breakfast.~');
create_item(c, q'~Vegetarian Roasted Vegetable Frittata~', q'~A fluffy egg frittata packed with oven-roasted zucchini, sweet bell peppers, caramelized onions, and tangy feta cheese. Baked until golden and sliced into generous wedges, each serving is garnished with fresh basil and served warm with a side of mixed greens tossed in a light vinaigrette. This savory breakfast is perfect for brunch gatherings or a leisurely morning meal.~');
create_item(c, q'~Vegetarian Spinach ~' || chr(38) || q'~ Feta Breakfast Muffin~', q'~Savory muffin packed with sautéed spinach, crumbled feta cheese, and sliced scallions. Served warm for a grab-and-go vegetarian breakfast.~');
create_item(c, q'~Vegetarian Spinach ~' || chr(38) || q'~ Feta Breakfast Pizza~', q'~Crispy flatbread topped with scrambled eggs, sautéed spinach, crumbled feta, and cherry tomatoes. Baked until golden and served warm for a unique vegetarian breakfast.~');
create_item(c, q'~Vegetarian Spinach ~' || chr(38) || q'~ Feta Breakfast Wrap~', q'~Whole wheat wrap filled with fluffy scrambled eggs, sautéed spinach, and crumbled feta cheese. Served warm with a side of roasted potatoes and a fresh tomato salsa. This portable vegetarian breakfast option is both nutritious and flavorful, ideal for busy mornings.~');
create_item(c, q'~Vegetarian Spinach ~' || chr(38) || q'~ Mushroom Breakfast Muffin~', q'~Savory muffin packed with sautéed spinach, earthy mushrooms, and sharp cheddar cheese. Served warm for a grab-and-go vegetarian breakfast.~');
create_item(c, q'~Vegetarian Spinach ~' || chr(38) || q'~ Tomato Quiche~', q'~A flaky pastry crust filled with fluffy farm eggs, sautéed baby spinach, juicy cherry tomatoes, and nutty Swiss cheese. Baked until set and golden, then sliced and served warm with a side of herbed potatoes and fresh fruit. The combination of creamy filling and crisp crust makes this classic vegetarian quiche a breakfast favorite.~');
create_item(c, q'~Vegetarian Sweet Corn ~' || chr(38) || q'~ Zucchini Pancakes~', q'~Golden pancakes made with sweet corn kernels, shredded zucchini, and sliced scallions. Each pancake is pan-fried until crisp on the edges and tender inside, then served with tangy sour cream and spicy homemade salsa. Garnished with fresh cilantro and a wedge of lime, these savory vegetarian pancakes are a flavorful breakfast treat.~');
create_item(c, q'~Vegetarian Tomato ~' || chr(38) || q'~ Basil Breakfast Muffin~', q'~Savory muffin packed with roasted tomatoes, fresh basil leaves, and creamy mozzarella cheese. Served warm for a grab-and-go vegetarian breakfast.~');
create_item(c, q'~Vegetarian Tomato ~' || chr(38) || q'~ Basil Breakfast Pizza~', q'~Crispy flatbread topped with fluffy scrambled eggs, juicy cherry tomatoes, creamy mozzarella cheese, and fresh basil leaves. Baked until golden and served warm with a drizzle of olive oil and a sprinkle of sea salt. This unique vegetarian breakfast pizza is both flavorful and visually appealing.~');
create_item(c, q'~Vegetarian Zucchini ~' || chr(38) || q'~ Parmesan Frittata~', q'~A fluffy egg frittata packed with shredded zucchini, nutty Parmesan cheese, and fresh basil. Baked until golden and sliced into wedges, each serving is garnished with a dollop of sour cream and a sprinkle of chives. This light vegetarian breakfast is both nutritious and flavorful.~');
create_item(c, q'~Venezuelan Perico~', q'~Scrambled eggs cooked with ripe tomatoes, sweet onions, and colorful bell peppers, served with warm arepas and fresh cheese. A vibrant Venezuelan breakfast, often enjoyed with avocado slices and hot sauce.~');
create_item(c, q'~Vietnamese Bánh Mì Op La~', q'~Crispy French baguette filled with sunny-side-up eggs, pickled daikon and carrots, fresh cucumber slices, cilantro, and a drizzle of savory soy sauce. A fusion of French and Vietnamese flavors, often served with a side of spicy chili sauce for an extra kick.~');


    select count(*) into l_count 
    from menu_items
    where category_id = l_categories(c);

    dbms_output.put_line('Created ' || l_count || ' menu items for category: ' || c);    

    commit;


exception
    when others then
        dbms_output.put_line(sqlerrm);
end;
/


    

