prompt loading menu items for category: Desserts
prompt script generated: 2025-08-17 21:10:29

set feedback on;
set serveroutput on;

declare

    l_count number;
    c menu_categories.category_name%type;

    type t_category_ids is table of integer index by varchar2(100);
    l_categories t_category_ids;

    procedure load_categories_array
    is
    begin
        l_categories := t_category_ids(for r in (select category_name, category_id from menu_categories) index r.category_name => r.category_id);
    end load_categories_array;

     procedure create_item(
        p_category_name in varchar2, 
        p_item_name in varchar2, 
        p_description in varchar2, 
        p_created_by in varchar2 default 'sample')
     is
        l_category_id integer := l_categories(p_category_name);
     begin     
        savepoint new_menu_item;

        insert into menu_items (item_name, category_id, item_description, created_by)
        values (p_item_name, l_category_id, p_description, p_created_by);
    exception
        when others then
            rollback to new_menu_item;
            dbms_output.put_line('Error inserting item: ' || p_item_name || ' SQLERRM: ' || sqlerrm);            
     end create_item;

begin

    load_categories_array;
 

    c := 'Desserts';
    delete menu_items 
    where category_id = l_categories(c);

    dbms_output.put_line('Deleted ' || sql%rowcount || ' existing menu items for category: ' || c);

 


create_item(c, q'~Affogato~', q'~A simple yet elegant Italian dessert where a scoop of creamy vanilla gelato is "drowned" with a shot of hot, freshly brewed espresso, creating a delightful contrast of temperatures and flavors.~');
create_item(c, q'~Alfajores~', q'~South American shortbread cookies sandwiched with a layer of dulce de leche and often rolled in coconut or dusted with powdered sugar. Tender, crumbly, and sweet.~');
create_item(c, q'~Almond Amaretto Cake~', q'~Tender almond cake infused with amaretto liqueur, filled with almond cream and topped with toasted almond slivers for a sophisticated treat.~');
create_item(c, q'~Almond Biscotti~', q'~Crunchy twice-baked Italian cookies studded with toasted almonds, perfect for dipping in coffee or dessert wine. Their crisp texture and nutty flavor make them a classic treat.~');
create_item(c, q'~Almond Blueberry Cake~', q'~Almond cake filled with blueberry compote and almond cream, topped with fresh blueberries and sliced almonds.~');
create_item(c, q'~Almond Joy Cookie~', q'~Chewy coconut cookies loaded with chocolate chips and toasted almonds, inspired by the classic candy bar.~');
create_item(c, q'~Almond Joy Layer Cake~', q'~Coconut cake filled with almond cream and chocolate ganache, topped with toasted almonds and coconut flakes.~');
create_item(c, q'~Almond Joy Pie~', q'~Chocolate custard layered with coconut and toasted almonds in a cookie crust, inspired by the classic candy bar.~');
create_item(c, q'~Almond Lemon Cake~', q'~Almond cake filled with lemon cream and almond buttercream, topped with sliced almonds and lemon zest.~');
create_item(c, q'~Almond Raspberry Cake~', q'~Almond cake filled with raspberry preserves and almond cream, topped with fresh raspberries and sliced almonds.~');
create_item(c, q'~Amaretto Almond Cheesecake~', q'~Smooth cheesecake flavored with amaretto liqueur and almond extract, baked on an almond cookie crust and topped with toasted sliced almonds.~');
create_item(c, q'~Angel Food Cake~', q'~A light and airy sponge cake made with whipped egg whites, sugar, and flour, known for its fluffy texture and subtle sweetness. Often served with berries or a dusting of powdered sugar.~');
create_item(c, q'~Anzac Biscuit~', q'~A traditional Australian and New Zealand cookie made with rolled oats, coconut, golden syrup, and butter. Crisp, chewy, and with a caramelized flavor.~');
create_item(c, q'~Apple Blackberry Almond Pie~', q'~Tender apples, blackberries, and almond cream baked together in a golden crust, finished with toasted almond flakes.~');
create_item(c, q'~Apple Blackberry Pie~', q'~Tender apples and blackberries baked together in a golden crust, offering a vibrant, summery flavor.~');
create_item(c, q'~Apple Caramel Pie~', q'~Tender apples layered with gooey caramel in a golden crust, finished with a sprinkle of sea salt.~');
create_item(c, q'~Apple Cinnamon Cake~', q'~Spiced apple cake layered with cinnamon cream and apple compote, finished with caramelized apple slices.~');
create_item(c, q'~Apple Cranberry Pie~', q'~Tender apples and tart cranberries baked together in a golden crust, offering a harmonious blend of sweet and tangy flavors.~');
create_item(c, q'~Apple Cranberry Walnut Pie~', q'~Tender apples, tart cranberries, and toasted walnuts baked together in a golden crust, finished with a cinnamon streusel topping.~');
create_item(c, q'~Apple Crumble~', q'~Warm baked apples tossed with sugar and cinnamon, topped with a crumbly mixture of flour, butter, and brown sugar. Baked until bubbling and golden, served with custard or ice cream.~');
create_item(c, q'~Apple Hazelnut Pie~', q'~Tender apples and roasted hazelnuts baked in a golden crust, finished with a cinnamon streusel topping.~');
create_item(c, q'~Apple Pie~', q'~Classic American dessert with a flaky pastry crust filled with spiced apples, baked until golden and served warm with a scoop of vanilla ice cream.~');
create_item(c, q'~Apple Pie Supreme~', q'~Classic double-crust pie brimming with tender, cinnamon-spiced apples, baked until golden and bubbling. Served warm with a scoop of vanilla ice cream for a comforting finish.~');
create_item(c, q'~Apple Walnut Pie~', q'~Tender apples and toasted walnuts baked in a golden crust, finished with a cinnamon streusel topping.~');
create_item(c, q'~Apricot Almond Cake~', q'~Almond cake filled with apricot preserves and almond cream, topped with glazed apricot halves and toasted almond flakes.~');
create_item(c, q'~Apricot Hazelnut Pie~', q'~Sweet apricots simmered with honey and layered over a hazelnut frangipane, all nestled in a crisp pastry shell.~');
create_item(c, q'~Apricot Pistachio Cookie~', q'~Soft cookies filled with chewy dried apricots and crunchy pistachios, delivering a sophisticated blend of sweet and nutty flavors.~');
create_item(c, q'~Apricot Pistachio Pie~', q'~Sweet apricots and crunchy pistachios layered in a crisp crust, finished with a honey glaze.~');
create_item(c, q'~Arroz con Leche~', q'~A traditional Spanish and Latin American rice pudding made by simmering rice with milk, sugar, and cinnamon until creamy. Sometimes garnished with raisins or citrus zest.~');
create_item(c, q'~Baileys Irish Cream Cheesecake~', q'~A luscious cheesecake infused with Baileys Irish Cream liqueur, baked on a chocolate cookie crust and topped with chocolate ganache and whipped cream.~');
create_item(c, q'~Baklava~', q'~A rich, sweet pastry made of layers of flaky phyllo dough filled with finely chopped nuts, such as pistachios or walnuts, and sweetened with honey or syrup. Finished with a fragrant hint of cinnamon or clove and cut into diamond shapes.~');
create_item(c, q'~Bakso~', q'~Sweet Indonesian dessert balls made from glutinous rice flour, filled with palm sugar and sometimes coconut, boiled until chewy and served in sweet syrup.~');
create_item(c, q'~Banana Caramel Cake~', q'~Moist banana cake layered with luscious caramel frosting and finished with caramelized banana slices for a comforting, nostalgic flavor.~');
create_item(c, q'~Banana Cream Pie~', q'~Layers of ripe banana slices and smooth vanilla custard in a buttery crust, crowned with whipped cream and a sprinkle of toasted coconut.~');
create_item(c, q'~Banana Nut Cookie~', q'~Soft cookies made with ripe bananas and crunchy walnuts, delivering a moist texture and a comforting, banana bread-inspired flavor.~');
create_item(c, q'~Banana Toffee Pie~', q'~Layers of sliced bananas and creamy toffee in a crisp crust, topped with whipped cream and toffee bits.~');
create_item(c, q'~Banoffee Pie~', q'~A British dessert pie with a buttery biscuit crust, layered with sliced bananas, luscious toffee caramel, and clouds of whipped cream. Sometimes topped with chocolate shavings for extra indulgence.~');
create_item(c, q'~Barfi~', q'~A traditional Indian sweet made from condensed milk and sugar, cooked until thick and cut into squares. Often flavored with cardamom, nuts, or coconut, and garnished with edible silver leaf.~');
create_item(c, q'~Basbousa~', q'~A moist, sweet semolina cake from the Middle East, soaked in simple syrup and often flavored with rose or orange blossom water. Topped with almonds or coconut.~');
create_item(c, q'~Berry Smoothie Bowl~', q'~A thick, vibrant smoothie made from blended berries, banana, and yogurt, poured into a bowl and topped with fresh berries, sliced fruit, crunchy seeds, and a sprinkle of granola for added texture.~');
create_item(c, q'~Bibingka~', q'~A Filipino coconut rice cake baked in banana leaves, resulting in a soft, slightly chewy texture. Topped with salted egg, cheese, and grated coconut for a sweet-savory flavor.~');
create_item(c, q'~Bingsu~', q'~A popular Korean shaved ice dessert topped with sweetened condensed milk, fruit, red beans, mochi, and sometimes ice cream. Light, refreshing, and customizable.~');
create_item(c, q'~Black Forest Cake~', q'~A German chocolate sponge cake layered with whipped cream and cherries, soaked with cherry liqueur, and decorated with chocolate shavings and more cherries.~');
create_item(c, q'~Black Forest Cheesecake~', q'~A chocolate cheesecake layered with sweet cherry compote and whipped cream, set on a chocolate cookie crust and garnished with chocolate curls and cherries.~');
create_item(c, q'~Black Forest Mousse Cake~', q'~Chocolate sponge cake layered with cherry mousse and whipped cream, finished with chocolate shavings and cherries.~');
create_item(c, q'~Black Forest Pie~', q'~Layers of chocolate custard, cherry compote, and whipped cream in a chocolate crust, garnished with chocolate curls and cherries.~');
create_item(c, q'~Blackberry Almond Pie~', q'~Luscious blackberries layered over a delicate almond cream, all nestled in a buttery crust. Finished with toasted almond flakes for added crunch.~');
create_item(c, q'~Blackberry Lavender Cake~', q'~Lavender-scented sponge cake layered with blackberry compote and lavender cream, finished with fresh blackberries and edible flowers.~');
create_item(c, q'~Blueberry Cheesecake~', q'~Classic cheesecake topped with a vibrant blueberry compote, featuring plump, juicy berries and a hint of lemon over a crisp graham cracker base.~');
create_item(c, q'~Blueberry Crumble Pie~', q'~Juicy blueberries nestled in a flaky crust, topped with a buttery oat crumble that bakes to a crisp, golden perfection. Each bite bursts with sweet-tart berry flavor.~');
create_item(c, q'~Blueberry Lemon Cake~', q'~Lemon cake studded with juicy blueberries, layered with lemon cream and blueberry compote, finished with a lemon glaze.~');
create_item(c, q'~Blueberry Muffin Cookie~', q'~Soft cookies bursting with juicy blueberries and topped with a crunchy streusel, reminiscent of a classic blueberry muffin.~');
create_item(c, q'~Boston Cream Pie~', q'~A classic American dessert with layers of light sponge cake filled with smooth vanilla pastry cream and topped with a glossy chocolate ganache.~');
create_item(c, q'~Bread Pudding~', q'~A homey dessert made from cubes of stale bread soaked in a rich custard of eggs, milk, sugar, and spices, then baked until golden. Often includes raisins or nuts and served with a warm sauce.~');
create_item(c, q'~Bread and Butter Pudding~', q'~A British dessert of buttered bread slices layered in a dish, soaked in a sweet egg custard with raisins or currants, and baked until golden and puffed. Finished with a sprinkle of nutmeg or cinnamon.~');
create_item(c, q'~Brown Butter Pecan Cookie~', q'~Chewy cookies made with nutty brown butter and loaded with toasted pecans, offering a rich, caramelized flavor and a satisfying crunch.~');
create_item(c, q'~Brownie~', q'~A dense, fudgy chocolate cake square with a crackly top and rich, moist interior. Sometimes studded with nuts or chocolate chips, brownies are beloved for their deep cocoa flavor and chewy texture.~');
create_item(c, q'~Buttermilk Pie~', q'~A traditional Southern dessert featuring a creamy, tangy custard made with buttermilk, eggs, and sugar, baked in a flaky pie shell and often dusted with nutmeg.~');
create_item(c, q'~Cannoli~', q'~A classic Sicilian dessert consisting of crisp, fried pastry tubes filled with a creamy, sweetened ricotta cheese mixture, often studded with chocolate chips or candied fruit. The ends are typically dusted with powdered sugar or dipped in crushed pistachios.~');
create_item(c, q'~Caramel Apple Cake~', q'~Spiced apple cake layered with creamy caramel frosting and studded with tender apple pieces, evoking the flavors of a classic caramel apple.~');
create_item(c, q'~Caramel Apple Cookie~', q'~Chewy cookies with bits of dried apple and swirls of caramel, evoking the flavors of a classic caramel apple in a portable form.~');
create_item(c, q'~Caramel Apple Mousse Cake~', q'~Spiced apple cake layered with caramel mousse and apple compote, finished with caramel drizzle and apple slices.~');
create_item(c, q'~Caramel Apple Spice Cake~', q'~Spiced apple cake layered with caramel cream and apple compote, finished with caramel drizzle and apple slices.~');
create_item(c, q'~Caramel Banana Cake~', q'~Banana cake layered with caramel cream and banana slices, finished with caramel drizzle and banana chips.~');
create_item(c, q'~Caramel Banana Pie~', q'~Layers of sliced bananas and creamy caramel in a crisp shell, finished with whipped cream and caramel drizzle.~');
create_item(c, q'~Caramel Chocolate Chip Cookie~', q'~Chewy cookies filled with gooey caramel and melty chocolate chips, creating a decadent, melt-in-your-mouth treat.~');
create_item(c, q'~Caramel Hazelnut Cake~', q'~Hazelnut cake layered with caramel cream and hazelnut buttercream, finished with caramel drizzle and toasted hazelnuts.~');
create_item(c, q'~Caramel Macadamia Cake~', q'~Buttery cake filled with caramel cream and toasted macadamia nuts, finished with caramel drizzle and macadamia halves.~');
create_item(c, q'~Caramel Macadamia Pie~', q'~Buttery caramel filling studded with roasted macadamia nuts, baked in a golden crust for a sweet-salty treat.~');
create_item(c, q'~Caramel Pecan Cake~', q'~Buttery cake layered with caramel cream and toasted pecans, finished with caramel drizzle and pecan halves.~');
create_item(c, q'~Caramel Pecan Turtle Cookie~', q'~Chewy cookies topped with gooey caramel, toasted pecans, and a drizzle of chocolate, inspired by classic turtle candies.~');
create_item(c, q'~Caramel Snickerdoodle Cookie~', q'~Soft snickerdoodle cookies with a gooey caramel center, dusted with cinnamon sugar for a sweet-spicy twist.~');
create_item(c, q'~Carrot Cake~', q'~A spiced cake made with grated carrots, walnuts, and warm spices, layered with rich cream cheese frosting. Moist and flavorful, often garnished with nuts or carrot decorations.~');
create_item(c, q'~Carrot Pineapple Cake~', q'~Moist carrot cake with pineapple chunks, layered with tangy cream cheese frosting and finished with toasted coconut.~');
create_item(c, q'~Cassata~', q'~A traditional Sicilian cake made with layers of sponge cake soaked in liqueur, sweet ricotta cheese, candied fruit, and a covering of marzipan and colorful icing.~');
create_item(c, q'~Chai Spice Cookie~', q'~Soft cookies infused with chai spices like cinnamon, cardamom, ginger, and cloves, offering a warm, aromatic flavor and a comforting texture.~');
create_item(c, q'~Charlotte~', q'~A classic French dessert made by lining a mold with ladyfingers or sponge cake and filling it with fruit mousse, custard, or Bavarian cream. Chilled and unmolded for serving.~');
create_item(c, q'~Che~', q'~A Vietnamese sweet dessert soup or pudding, made with a variety of ingredients such as beans, jellies, fruit, and coconut milk. Served cold or at room temperature.~');
create_item(c, q'~Cherry Almond Cake~', q'~Almond cake layered with cherry preserves and almond cream, finished with a crown of glazed cherries and toasted almonds.~');
create_item(c, q'~Cherry Almond Cookie~', q'~Tender cookies filled with dried cherries and slivered almonds, offering a delightful balance of tart fruit and nutty richness.~');
create_item(c, q'~Cherry Almond Pie~', q'~Tart cherries and almond cream baked in a golden crust, finished with toasted almond flakes.~');
create_item(c, q'~Cherry Clafoutis~', q'~A rustic French dessert of fresh cherries baked in a thick, flan-like batter. The result is a custardy, lightly sweet treat, dusted with powdered sugar and served warm.~');
create_item(c, q'~Cherry Lattice Pie~', q'~Plump, tart cherries enveloped in a glossy filling, encased in a flaky crust with a decorative lattice top. Finished with a dusting of sugar for a beautiful presentation.~');
create_item(c, q'~Chess Pie~', q'~A classic Southern pie with a buttery, flaky crust and a sweet, dense custard filling made from eggs, sugar, butter, and a hint of cornmeal or vinegar.~');
create_item(c, q'~Chestnut Cream Cake~', q'~Delicate chestnut sponge cake layered with chestnut cream and whipped cream, topped with glazed chestnuts.~');
create_item(c, q'~Chocolate Almond Biscotti~', q'~Crunchy biscotti packed with toasted almonds and chocolate chunks, perfect for dipping in coffee or dessert wine.~');
create_item(c, q'~Chocolate Almond Cake~', q'~Chocolate cake filled with almond cream and chocolate ganache, topped with toasted almonds and chocolate curls.~');
create_item(c, q'~Chocolate Almond Cookie~', q'~Rich chocolate cookies packed with toasted almond slivers, offering a crunchy texture and a deep, nutty flavor.~');
create_item(c, q'~Chocolate Almond Mousse Cake~', q'~Chocolate cake layered with almond mousse and chocolate ganache, finished with toasted almonds and chocolate curls.~');
create_item(c, q'~Chocolate Almond Pie~', q'~Rich chocolate custard and toasted almonds in a buttery crust, topped with whipped cream and almond slivers.~');
create_item(c, q'~Chocolate Almond Sandwich Cookie~', q'~Crisp chocolate cookies sandwiched with creamy almond filling, offering a decadent, nutty treat.~');
create_item(c, q'~Chocolate Banana Cake~', q'~Chocolate cake layered with banana cream and chocolate ganache, finished with caramelized banana slices and chocolate curls.~');
create_item(c, q'~Chocolate Banana Hazelnut Pie~', q'~Layers of sliced bananas, creamy chocolate custard, and roasted hazelnuts in a crisp shell, finished with whipped cream.~');
create_item(c, q'~Chocolate Banana Pie~', q'~Layers of sliced bananas and creamy chocolate custard in a crisp shell, finished with whipped cream and chocolate shavings.~');
create_item(c, q'~Chocolate Banana Walnut Pie~', q'~Layers of sliced bananas, creamy chocolate custard, and toasted walnuts in a crisp shell, finished with whipped cream.~');
create_item(c, q'~Chocolate Blackberry Cake~', q'~Chocolate cake filled with blackberry preserves and chocolate cream, topped with fresh blackberries and chocolate shavings.~');
create_item(c, q'~Chocolate Blueberry Cake~', q'~Chocolate cake filled with blueberry compote and chocolate cream, topped with fresh blueberries and chocolate shavings.~');
create_item(c, q'~Chocolate Blueberry Pie~', q'~Fudgy chocolate filling and juicy blueberries nestled in a cookie crust, finished with whipped cream and chocolate curls.~');
create_item(c, q'~Chocolate Bourbon Pecan Pie~', q'~Toasted pecans and rich chocolate chunks in a bourbon-infused custard, baked in a buttery shell for a grown-up twist on a classic.~');
create_item(c, q'~Chocolate Cake~', q'~Rich, moist chocolate cake layered with smooth chocolate frosting and finished with a glossy ganache. Perfect for chocolate lovers and special occasions.~');
create_item(c, q'~Chocolate Caramel Biscotti~', q'~Crunchy biscotti filled with gooey caramel and chocolate chunks, offering a decadent, melt-in-your-mouth treat.~');
create_item(c, q'~Chocolate Caramel Cake~', q'~Chocolate cake layered with gooey caramel and chocolate buttercream, finished with caramel drizzle and chocolate shards.~');
create_item(c, q'~Chocolate Caramel Cookie~', q'~Fudgy chocolate cookies with pockets of gooey caramel, creating a decadent, melt-in-your-mouth treat.~');
create_item(c, q'~Chocolate Caramel Pecan Cookie~', q'~Chewy chocolate cookies topped with gooey caramel and toasted pecans, inspired by classic turtle candies.~');
create_item(c, q'~Chocolate Caramel Pie~', q'~Layers of rich chocolate custard and gooey caramel in a crisp shell, topped with whipped cream and chocolate shavings.~');
create_item(c, q'~Chocolate Caramel Sandwich Cookie~', q'~Crisp chocolate cookies sandwiched with gooey caramel, offering a decadent, melt-in-your-mouth treat.~');
create_item(c, q'~Chocolate Cherry Almond Cookie~', q'~Chewy cookies packed with dried cherries, toasted almonds, and chocolate chips, delivering a rich, fruity, and nutty experience.~');
create_item(c, q'~Chocolate Cherry Almond Pie~', q'~Fudgy chocolate filling swirled with cherry preserves and toasted almonds in a cookie crust, finished with whipped cream.~');
create_item(c, q'~Chocolate Cherry Cookie~', q'~Fudgy chocolate cookies packed with dried cherries, delivering a rich, fruity twist and a chewy, decadent texture.~');
create_item(c, q'~Chocolate Cherry Layer Cake~', q'~Chocolate cake filled with cherry preserves and chocolate mousse, topped with fresh cherries and chocolate curls.~');
create_item(c, q'~Chocolate Cherry Mousse Cake~', q'~Chocolate cake layered with cherry mousse and chocolate ganache, finished with fresh cherries and chocolate curls.~');
create_item(c, q'~Chocolate Cherry Pie~', q'~Fudgy chocolate filling swirled with cherry preserves in a cookie crust, finished with fresh cherries and chocolate curls.~');
create_item(c, q'~Chocolate Chess Pie~', q'~Rich chocolate custard baked in a flaky crust, with a crackly top and a fudgy interior. A Southern classic with a cocoa twist.~');
create_item(c, q'~Chocolate Chili Cake~', q'~Dark chocolate cake with a hint of chili, layered with chocolate ganache and finished with candied chili slices for a spicy kick.~');
create_item(c, q'~Chocolate Chip Cookie~', q'~A classic American cookie made with buttery dough and loaded with semi-sweet chocolate chips. Crispy on the edges and chewy in the center.~');
create_item(c, q'~Chocolate Chipotle Cookie~', q'~Fudgy chocolate cookies with a hint of smoky chipotle pepper, delivering a subtle heat and a bold, complex flavor.~');
create_item(c, q'~Chocolate Chunk Biscotti~', q'~Crunchy biscotti loaded with oversized chunks of milk and dark chocolate, delivering a fudgy, indulgent experience in every bite.~');
create_item(c, q'~Chocolate Chunk Cookie~', q'~Soft cookies loaded with oversized chunks of milk and dark chocolate, delivering a fudgy, indulgent experience in every bite.~');
create_item(c, q'~Chocolate Coconut Cake~', q'~Chocolate cake filled with coconut cream and chocolate ganache, finished with toasted coconut flakes.~');
create_item(c, q'~Chocolate Coconut Chip Cookie~', q'~Chewy chocolate cookies loaded with sweet coconut flakes and chocolate chips, offering a tropical flavor and a decadent texture.~');
create_item(c, q'~Chocolate Coconut Cookie~', q'~Fudgy chocolate cookies packed with shredded coconut, offering a chewy texture and a rich, tropical flavor.~');
create_item(c, q'~Chocolate Coconut Layer Cake~', q'~Chocolate cake filled with coconut cream and chocolate ganache, finished with toasted coconut flakes.~');
create_item(c, q'~Chocolate Coconut Macaroon~', q'~Chewy coconut macaroons dipped in rich chocolate, offering a tropical flavor and a decadent finish.~');
create_item(c, q'~Chocolate Coconut Mousse Cake~', q'~Chocolate cake layered with coconut mousse and chocolate ganache, finished with toasted coconut flakes.~');
create_item(c, q'~Chocolate Coconut Pie~', q'~Creamy chocolate filling layered with toasted coconut in a cookie crust, topped with whipped cream and more coconut.~');
create_item(c, q'~Chocolate Dipped Macaroons~', q'~Chewy coconut macaroons dipped in rich dark chocolate, offering a delightful contrast between sweet coconut and bittersweet chocolate. Each bite is moist and decadent.~');
create_item(c, q'~Chocolate Eclair~', q'~A classic French pastry made from choux dough, filled with rich vanilla pastry cream and topped with a glossy chocolate glaze. Light, airy, and indulgent.~');
create_item(c, q'~Chocolate Espresso Crinkle Cookie~', q'~Dark chocolate cookies with a hint of espresso, rolled in powdered sugar and baked to create a crackled, crinkly surface.~');
create_item(c, q'~Chocolate Fudge Cake~', q'~A rich, moist chocolate cake layered with velvety chocolate fudge frosting and finished with glossy ganache. Each bite delivers deep cocoa flavor and a melt-in-your-mouth texture.~');
create_item(c, q'~Chocolate Hazelnut Banana Pie~', q'~Silky chocolate filling blended with roasted hazelnuts and sliced bananas in a crisp shell, topped with whipped cream.~');
create_item(c, q'~Chocolate Hazelnut Banana Walnut Pie~', q'~Silky chocolate filling blended with roasted hazelnuts, sliced bananas, and toasted walnuts in a crisp shell, topped with whipped cream.~');
create_item(c, q'~Chocolate Hazelnut Banana Walnut Raspberry Pie~', q'~Silky chocolate filling blended with roasted hazelnuts, sliced bananas, toasted walnuts, and raspberry preserves in a crisp shell, topped with whipped cream.~');
create_item(c, q'~Chocolate Hazelnut Biscotti~', q'~Crunchy biscotti packed with toasted hazelnuts and chocolate chunks, offering a deep, nutty flavor and a satisfying crunch.~');
create_item(c, q'~Chocolate Hazelnut Cheesecake~', q'~A decadent cheesecake swirled with chocolate hazelnut spread, set on a chocolate-hazelnut crust and topped with toasted hazelnuts and chocolate drizzle.~');
create_item(c, q'~Chocolate Hazelnut Cookie~', q'~Rich chocolate cookies packed with toasted hazelnuts, offering a crunchy texture and a deep, nutty flavor.~');
create_item(c, q'~Chocolate Hazelnut Layer Cake~', q'~Chocolate cake filled with hazelnut cream and chocolate ganache, finished with toasted hazelnuts and chocolate shards.~');
create_item(c, q'~Chocolate Hazelnut Mousse Cake~', q'~Chocolate cake layered with hazelnut mousse and chocolate ganache, finished with toasted hazelnuts and chocolate curls.~');
create_item(c, q'~Chocolate Hazelnut Pie~', q'~Silky chocolate filling blended with roasted hazelnuts in a crisp shell, topped with whipped cream and hazelnut praline.~');
create_item(c, q'~Chocolate Hazelnut Raspberry Almond Pie~', q'~Fudgy chocolate filling swirled with raspberry preserves, roasted hazelnuts, and toasted almonds in a cookie crust, finished with whipped cream.~');
create_item(c, q'~Chocolate Hazelnut Raspberry Pie~', q'~Silky chocolate filling blended with roasted hazelnuts and raspberry preserves in a crisp shell, topped with whipped cream.~');
create_item(c, q'~Chocolate Hazelnut Sandwich Cookie~', q'~Crisp chocolate cookies sandwiched with creamy hazelnut spread, offering a decadent, Nutella-inspired experience.~');
create_item(c, q'~Chocolate Lemon Cake~', q'~Chocolate cake filled with lemon cream and chocolate ganache, topped with candied lemon slices and chocolate curls.~');
create_item(c, q'~Chocolate Macadamia Biscotti~', q'~Crunchy biscotti packed with buttery macadamia nuts and chocolate chunks, perfect for dipping in coffee or dessert wine.~');
create_item(c, q'~Chocolate Macadamia Cookie~', q'~Rich chocolate cookies packed with buttery macadamia nuts, offering a luxurious, tropical flavor and a satisfying crunch.~');
create_item(c, q'~Chocolate Marble Cheesecake~', q'~A decadent cheesecake with a marbled blend of creamy vanilla and rich chocolate batters, baked on a chocolate cookie crust and finished with chocolate shavings.~');
create_item(c, q'~Chocolate Marshmallow Biscotti~', q'~Crunchy biscotti filled with gooey marshmallow and chocolate chunks, offering a decadent, s’mores-inspired treat.~');
create_item(c, q'~Chocolate Marshmallow Cookie~', q'~Soft chocolate cookies with gooey marshmallow centers, offering a decadent, s’mores-inspired treat.~');
create_item(c, q'~Chocolate Mint Biscotti~', q'~Crunchy biscotti infused with cool mint and packed with chocolate chips, reminiscent of classic after-dinner mints.~');
create_item(c, q'~Chocolate Mint Cake~', q'~Chocolate cake layered with cool mint cream and chocolate ganache, finished with chocolate curls and mint leaves.~');
create_item(c, q'~Chocolate Mint Cookie~', q'~Rich chocolate cookies with a cool mint filling, reminiscent of classic after-dinner mints. Their fudgy texture and refreshing flavor are a crowd-pleaser.~');
create_item(c, q'~Chocolate Mint Pie~', q'~Cool mint mousse layered with rich chocolate ganache in a cookie crust, topped with whipped cream and chocolate shavings.~');
create_item(c, q'~Chocolate Mint Sandwich Cookie~', q'~Crisp chocolate cookies sandwiched with cool mint cream, reminiscent of classic after-dinner mints.~');
create_item(c, q'~Chocolate Mousse~', q'~Light and airy chocolate dessert made from whipped cream and rich chocolate, chilled until set and served in individual cups. Garnished with chocolate shavings.~');
create_item(c, q'~Chocolate Mousse Cake~', q'~Layers of airy chocolate mousse and moist chocolate sponge, finished with a glossy chocolate glaze and chocolate curls for a decadent experience.~');
create_item(c, q'~Chocolate Orange Biscotti~', q'~Crunchy twice-baked cookies infused with orange zest and studded with chocolate chunks, perfect for dipping in coffee or tea.~');
create_item(c, q'~Chocolate Orange Cake~', q'~Chocolate cake infused with orange zest, layered with orange cream and chocolate ganache, finished with candied orange peel.~');
create_item(c, q'~Chocolate Orange Cookie~', q'~Rich chocolate cookies infused with orange zest and topped with a drizzle of orange glaze, offering a sophisticated citrus-chocolate pairing.~');
create_item(c, q'~Chocolate Orange Mousse Cake~', q'~Chocolate cake layered with orange mousse and chocolate ganache, finished with candied orange peel and chocolate curls.~');
create_item(c, q'~Chocolate Orange Pie~', q'~Rich chocolate custard infused with orange zest in a crisp shell, garnished with candied orange slices.~');
create_item(c, q'~Chocolate Peanut Butter Biscotti~', q'~Crunchy biscotti packed with chocolate chips and swirls of creamy peanut butter, delivering a classic flavor combination and a decadent texture.~');
create_item(c, q'~Chocolate Peanut Butter Cake~', q'~Chocolate cake layered with creamy peanut butter frosting and finished with chocolate ganache and peanut butter cups.~');
create_item(c, q'~Chocolate Peanut Butter Cookie~', q'~Fudgy chocolate cookies swirled with creamy peanut butter, delivering a classic flavor combination and a decadent texture.~');
create_item(c, q'~Chocolate Peanut Butter Cup Cookie~', q'~Soft cookies packed with chopped peanut butter cups and chocolate chips, delivering a rich, candy-inspired treat.~');
create_item(c, q'~Chocolate Peanut Butter Pie~', q'~Decadent peanut butter mousse layered with rich chocolate ganache in a crisp cookie crust, topped with chopped peanuts and chocolate curls.~');
create_item(c, q'~Chocolate Peanut Butter Pretzel Cookie~', q'~Chewy cookies loaded with chocolate chips, peanut butter, and crunchy pretzel pieces, offering a sweet-salty flavor explosion.~');
create_item(c, q'~Chocolate Peanut Butter Sandwich Cookie~', q'~Crisp chocolate cookies sandwiched with creamy peanut butter, delivering a classic flavor combination and a decadent texture.~');
create_item(c, q'~Chocolate Pear Cake~', q'~Chocolate cake filled with poached pear slices and chocolate cream, topped with glazed pears and chocolate shavings.~');
create_item(c, q'~Chocolate Pistachio Cake~', q'~Chocolate cake layered with pistachio cream and chocolate ganache, finished with chopped pistachios and chocolate shards.~');
create_item(c, q'~Chocolate Pistachio Cookie~', q'~Rich chocolate cookies studded with roasted pistachios, offering a vibrant color and a unique, nutty flavor.~');
create_item(c, q'~Chocolate Pistachio Layer Cake~', q'~Chocolate cake layered with pistachio cream and chocolate ganache, finished with chopped pistachios and chocolate curls.~');
create_item(c, q'~Chocolate Pistachio Mousse Cake~', q'~Chocolate cake layered with pistachio mousse and chocolate ganache, finished with chopped pistachios and chocolate curls.~');
create_item(c, q'~Chocolate Pistachio Pie~', q'~Silky chocolate custard and crunchy pistachios in a crisp shell, topped with whipped cream and chopped pistachios.~');
create_item(c, q'~Chocolate Raspberry Almond Pie~', q'~Fudgy chocolate filling swirled with raspberry preserves and toasted almonds in a cookie crust, finished with whipped cream.~');
create_item(c, q'~Chocolate Raspberry Cake~', q'~Rich chocolate cake layered with raspberry jam and chocolate ganache, finished with fresh raspberries and chocolate shavings.~');
create_item(c, q'~Chocolate Raspberry Cookie~', q'~Fudgy chocolate cookies filled with sweet raspberry jam, creating a rich, fruity twist and a decadent texture.~');
create_item(c, q'~Chocolate Raspberry Pie~', q'~Fudgy chocolate filling swirled with raspberry preserves in a crisp shell, finished with fresh raspberries and chocolate drizzle.~');
create_item(c, q'~Chocolate Silk Pie~', q'~A velvety chocolate mousse filling set in a crisp cookie crust, topped with clouds of whipped cream and chocolate shavings for a luxurious finish.~');
create_item(c, q'~Chocolate Soufflé~', q'~A light, airy baked dessert made with rich chocolate and whipped egg whites, resulting in a delicate, puffy texture. Served hot, often with a dusting of powdered sugar or a scoop of ice cream.~');
create_item(c, q'~Chocolate Strawberry Cake~', q'~Chocolate cake layered with strawberry jam and chocolate mousse, topped with fresh strawberries and chocolate curls.~');
create_item(c, q'~Chocolate Strawberry Pie~', q'~Fudgy chocolate filling topped with fresh strawberries in a cookie crust, finished with chocolate drizzle.~');
create_item(c, q'~Chocolate Toffee Pecan Cookie~', q'~Rich chocolate cookies loaded with crunchy toffee bits and toasted pecans, delivering a sweet, nutty, and caramelized flavor.~');
create_item(c, q'~Chocolate Walnut Biscotti~', q'~Crunchy biscotti packed with toasted walnuts and chocolate chunks, perfect for dipping in coffee or dessert wine.~');
create_item(c, q'~Chocolate Walnut Cake~', q'~Chocolate cake filled with walnut cream and chocolate ganache, finished with toasted walnuts and chocolate shards.~');
create_item(c, q'~Chocolate Walnut Cookie~', q'~Chewy chocolate cookies packed with toasted walnuts, offering a rich, nutty flavor and a satisfying crunch.~');
create_item(c, q'~Chocolate Walnut Mousse Cake~', q'~Chocolate cake layered with walnut mousse and chocolate ganache, finished with toasted walnuts and chocolate curls.~');
create_item(c, q'~Chocolate Walnut Sandwich Cookie~', q'~Crisp chocolate cookies sandwiched with creamy walnut filling, offering a decadent, nutty treat.~');
create_item(c, q'~Churros~', q'~Spanish fried dough pastries, crisp on the outside and soft inside, coated in cinnamon sugar and often served with a cup of thick, rich chocolate sauce for dipping.~');
create_item(c, q'~Cinnamon Roll Cake~', q'~Swirled cinnamon cake layered with cream cheese frosting and finished with a drizzle of vanilla glaze.~');
create_item(c, q'~Cinnamon Roll Cookie~', q'~Swirled cookies with layers of cinnamon sugar and a sweet vanilla glaze, capturing the essence of a classic cinnamon roll in a bite-sized form.~');
create_item(c, q'~Cinnamon Sugar Cookie~', q'~Soft cookies rolled in cinnamon sugar before baking, delivering a crackled surface and a warm, spicy flavor.~');
create_item(c, q'~Clafoutis~', q'~A rustic French dessert of fresh fruit, typically cherries, baked in a thick, pancake-like batter until puffed and golden. Served warm and dusted with powdered sugar.~');
create_item(c, q'~Classic New York Cheesecake~', q'~A rich, dense, and creamy cheesecake made with cream cheese, eggs, and sugar atop a buttery graham cracker crust. Baked to perfection and served plain or with a strawberry topping.~');
create_item(c, q'~Coconut Cream Pie~', q'~A flaky pie crust filled with creamy coconut custard, topped with whipped cream and toasted coconut flakes for a tropical, decadent dessert.~');
create_item(c, q'~Coconut Custard Pie~', q'~Rich coconut custard baked in a golden shell, finished with a layer of toasted coconut flakes for a tropical twist.~');
create_item(c, q'~Coconut Layer Cake~', q'~Fluffy coconut cake filled and frosted with coconut cream, finished with a generous coating of toasted coconut flakes for tropical flair.~');
create_item(c, q'~Coconut Lime Cookie~', q'~Tropical cookies combining sweet coconut flakes and tangy lime zest, finished with a light lime glaze for a refreshing, summery treat.~');
create_item(c, q'~Cranberry Oatmeal Cookie~', q'~Hearty oatmeal cookies filled with tart dried cranberries, offering a chewy texture and a comforting, wholesome flavor.~');
create_item(c, q'~Cranberry Orange Cake~', q'~Orange cake filled with cranberry compote and orange cream, finished with candied orange slices and sugared cranberries.~');
create_item(c, q'~Cranberry Orange Cookie~', q'~Tender cookies bursting with tart dried cranberries and fresh orange zest, finished with a sweet orange glaze.~');
create_item(c, q'~Cranberry Orange Pie~', q'~Tart cranberries and bright orange zest meld in a golden crust, creating a festive, vibrant dessert.~');
create_item(c, q'~Cranberry Pecan Pie~', q'~Tart cranberries and crunchy pecans in a sweet custard, baked in a golden shell for a festive treat.~');
create_item(c, q'~Cranberry Pistachio Biscotti~', q'~Crunchy biscotti filled with tart dried cranberries and roasted pistachios, offering a festive blend of flavors and colors.~');
create_item(c, q'~Cranberry Pistachio Cake~', q'~Pistachio cake filled with cranberry compote and pistachio cream, finished with sugared cranberries and chopped pistachios.~');
create_item(c, q'~Cranberry Pistachio Cookie~', q'~Festive cookies filled with tart dried cranberries and crunchy pistachios, offering a colorful and flavorful combination perfect for celebrations.~');
create_item(c, q'~Cranberry White Chocolate Biscotti~', q'~Crunchy biscotti filled with tart dried cranberries and creamy white chocolate chips, offering a festive and indulgent treat.~');
create_item(c, q'~Cranberry White Chocolate Cookie~', q'~Soft cookies filled with tart dried cranberries and creamy white chocolate chips, offering a festive and indulgent treat.~');
create_item(c, q'~Crème Brûlée~', q'~A decadent French dessert featuring a rich, silky vanilla custard base topped with a thin, crackly layer of caramelized sugar. Served chilled, the contrast between the creamy custard and crisp sugar topping is irresistible.~');
create_item(c, q'~Daifuku~', q'~A soft, round mochi (glutinous rice cake) stuffed with a sweet filling, usually red bean paste or fruit. Chewy and delicate, often dusted with potato starch.~');
create_item(c, q'~Dobos Torte~', q'~A Hungarian cake with multiple thin layers of sponge cake and chocolate buttercream, topped with a crisp caramel layer. Elegant and rich.~');
create_item(c, q'~Dorayaki~', q'~A Japanese confection consisting of two fluffy, pancake-like cakes sandwiched around a sweet red bean paste filling. Soft, moist, and perfect for snacking.~');
create_item(c, q'~Double Chocolate Chunk Cookie~', q'~A rich chocolate cookie base packed with oversized chunks of milk and dark chocolate, delivering a fudgy, indulgent experience in every bite.~');
create_item(c, q'~Dulce de Leche~', q'~A luscious, sweet caramel spread made by slowly simmering milk and sugar until thick and golden. Used as a filling or topping for cakes, cookies, and pastries.~');
create_item(c, q'~Dulce de Leche Cheesecake~', q'~Creamy cheesecake swirled with sweet, caramel-like dulce de leche, baked on a cinnamon graham crust and finished with a drizzle of more dulce de leche.~');
create_item(c, q'~Eclair~', q'~A delicate French pastry made from choux dough, baked until golden and hollow, then filled with smooth pastry cream and finished with a glossy chocolate glaze. Light, airy, and indulgent.~');
create_item(c, q'~Egg Tart~', q'~A delicate pastry shell filled with smooth, lightly sweetened egg custard, baked until just set. Popular in Chinese bakeries and often enjoyed with tea.~');
create_item(c, q'~Espresso Cheesecake~', q'~Bold espresso-infused cheesecake with a chocolate cookie crust, topped with chocolate-covered coffee beans and a dusting of cocoa powder.~');
create_item(c, q'~Espresso Cookie~', q'~Bold espresso-infused cookies with a tender crumb and a hint of cocoa, perfect for coffee lovers seeking a sophisticated treat.~');
create_item(c, q'~Financier~', q'~A small, moist French almond cake with a delicate crumb and a crisp, golden exterior. Traditionally baked in rectangular molds and enjoyed with tea or coffee.~');
create_item(c, q'~Flan~', q'~A creamy caramel custard dessert with a silky texture, made from eggs, milk, and sugar, baked in a caramel-lined mold and inverted to reveal a golden caramel sauce.~');
create_item(c, q'~Frozen Yogurt~', q'~A chilled dessert made from cultured yogurt, offering a tangy flavor and creamy texture. Served soft-serve style and often topped with fruit, nuts, or candy.~');
create_item(c, q'~Fruit Parfait~', q'~A layered dessert of fresh fruit, creamy yogurt or custard, and crunchy granola or cake, served in a tall glass for a colorful and refreshing treat.~');
create_item(c, q'~Fruit Sorbet~', q'~A refreshing frozen dessert made from pureed fruit, sugar, and water, churned until smooth and icy. Dairy-free and intensely flavorful, perfect as a palate cleanser or light dessert.~');
create_item(c, q'~Fruit Tart~', q'~Buttery tart shell filled with smooth pastry cream and topped with an array of fresh seasonal fruits. Glazed for a beautiful, glossy finish.~');
create_item(c, q'~Gelato~', q'~An Italian-style ice cream with a dense, creamy texture and intense flavor, made with less air and fat than traditional ice cream. Available in a variety of classic and creative flavors.~');
create_item(c, q'~German Chocolate Cake~', q'~A layered chocolate cake filled and topped with a rich coconut-pecan frosting. Sweet, nutty, and deeply chocolatey, with a moist crumb.~');
create_item(c, q'~Ginger Lemon Cookie~', q'~Soft cookies with a zesty lemon base and spicy ginger pieces, finished with a lemon glaze for a refreshing and aromatic treat.~');
create_item(c, q'~Gingerbread Cake~', q'~Spiced gingerbread cake layered with molasses cream and finished with gingerbread crumbs and candied ginger.~');
create_item(c, q'~Gingerbread Pie~', q'~Spiced gingerbread custard baked in a molasses-infused crust, topped with cinnamon whipped cream and candied ginger.~');
create_item(c, q'~Grasshopper Pie~', q'~A no-bake pie with a chocolate cookie crust and a creamy, mint-flavored filling made with crème de menthe and crème de cacao, often topped with whipped cream and chocolate shavings.~');
create_item(c, q'~Greek Yogurt Parfait~', q'~Layers of rich, creamy Greek yogurt alternated with fresh seasonal fruit, crunchy granola, and a drizzle of honey. Served in a tall glass for a refreshing and nutritious dessert or breakfast.~');
create_item(c, q'~Gulab Jamun~', q'~Soft, deep-fried milk-based dough balls soaked in a fragrant sugar syrup flavored with rose water or cardamom. Served warm and enjoyed during celebrations.~');
create_item(c, q'~Halo-Halo~', q'~A vibrant Filipino shaved ice dessert layered with sweetened beans, jellies, fruits, and leche flan, topped with evaporated milk and purple yam ice cream. Served in a tall glass for mixing.~');
create_item(c, q'~Hazelnut Chocolate Cookie~', q'~Soft cookies blended with roasted hazelnuts and swirls of chocolate, offering a nutty aroma and a luxurious, melt-in-your-mouth texture.~');
create_item(c, q'~Hazelnut Chocolate Mousse Cake~', q'~Hazelnut sponge cake layered with chocolate mousse and hazelnut cream, finished with chocolate glaze and hazelnut praline.~');
create_item(c, q'~Hazelnut Praline Cake~', q'~Decadent hazelnut sponge cake filled with crunchy praline and silky hazelnut buttercream, topped with caramelized hazelnuts for a nutty crunch.~');
create_item(c, q'~Hazelnut Praline Pie~', q'~Crunchy hazelnut praline layered over a smooth chocolate filling in a crisp pastry shell, topped with whipped cream and caramel drizzle.~');
create_item(c, q'~Honey Fig Cake~', q'~Tender honey cake layered with fig preserves and honey cream, topped with fresh figs and a drizzle of honey.~');
create_item(c, q'~Honey Lavender Cookie~', q'~Delicate cookies sweetened with honey and infused with fragrant lavender, offering a floral aroma and a subtly sweet flavor.~');
create_item(c, q'~Ice Cream Sundae~', q'~A classic dessert featuring scoops of ice cream topped with sauces, whipped cream, nuts, sprinkles, and a cherry. Customizable with endless flavor and topping combinations.~');
create_item(c, q'~Jalebi~', q'~Bright orange, spiral-shaped Indian sweets made by deep-frying fermented batter and soaking the crisp coils in saffron-infused sugar syrup. Sweet, sticky, and aromatic.~');
create_item(c, q'~Key Lime Cheesecake~', q'~A tangy, refreshing cheesecake made with key lime juice and zest, baked on a graham cracker crust and topped with whipped cream and lime slices.~');
create_item(c, q'~Key Lime Cookie~', q'~Tangy cookies infused with key lime juice and zest, finished with a sweet lime glaze for a refreshing, tropical treat.~');
create_item(c, q'~Key Lime Meringue Pie~', q'~Tangy key lime filling in a graham cracker crust, topped with billowy, golden-brown meringue. The perfect balance of sweet and tart.~');
create_item(c, q'~Key Lime Pie~', q'~A tangy, creamy pie made with key lime juice, sweetened condensed milk, and egg yolks in a crisp graham cracker crust. Topped with whipped cream or meringue for a refreshing finish.~');
create_item(c, q'~Kheer~', q'~An Indian rice pudding simmered with milk, sugar, and fragrant cardamom, often garnished with slivered almonds, pistachios, and golden raisins. Served chilled or warm.~');
create_item(c, q'~Knafeh~', q'~A Middle Eastern dessert made with shredded phyllo dough layered with sweet cheese or semolina, baked until golden, and soaked in fragrant sugar syrup. Garnished with pistachios.~');
create_item(c, q'~Kremes~', q'~A Hungarian dessert consisting of layers of crisp puff pastry filled with a thick, creamy vanilla custard. Cut into squares and dusted with powdered sugar.~');
create_item(c, q'~Kulfi~', q'~A dense, creamy Indian frozen dessert made from slowly simmered milk, flavored with cardamom, saffron, or pistachios, and molded into cones or sticks.~');
create_item(c, q'~Lamington~', q'~An Australian sponge cake cut into squares, dipped in chocolate icing, and rolled in desiccated coconut. Sometimes filled with jam or cream for extra richness.~');
create_item(c, q'~Lemon Almond Biscotti~', q'~Crunchy biscotti infused with fresh lemon zest and toasted almonds, offering a bright, nutty flavor and a satisfying crunch.~');
create_item(c, q'~Lemon Almond Cookie~', q'~Tender cookies infused with fresh lemon zest and toasted almonds, finished with a sweet lemon glaze.~');
create_item(c, q'~Lemon Blackberry Cake~', q'~Lemon cake filled with blackberry preserves and lemon cream, finished with fresh blackberries and lemon zest.~');
create_item(c, q'~Lemon Blackberry Pie~', q'~Bright lemon custard and juicy blackberries nestled in a golden crust, finished with a sweet glaze.~');
create_item(c, q'~Lemon Blueberry Biscotti~', q'~Crunchy biscotti bursting with fresh blueberries and bright lemon zest, finished with a sweet lemon glaze.~');
create_item(c, q'~Lemon Blueberry Cookie~', q'~Tender cookies bursting with fresh blueberries and bright lemon zest, finished with a sweet lemon glaze.~');
create_item(c, q'~Lemon Blueberry Cream Pie~', q'~Tangy lemon curd and juicy blueberries atop a smooth vanilla cream in a crisp shell, finished with whipped cream.~');
create_item(c, q'~Lemon Blueberry Layer Cake~', q'~Lemon cake layered with blueberry compote and lemon cream, finished with fresh blueberries and lemon zest.~');
create_item(c, q'~Lemon Blueberry Mousse Cake~', q'~Lemon cake layered with blueberry mousse and lemon cream, finished with fresh blueberries and lemon zest.~');
create_item(c, q'~Lemon Blueberry Oatmeal Cookie~', q'~Hearty oatmeal cookies bursting with fresh blueberries and bright lemon zest, finished with a sweet lemon glaze.~');
create_item(c, q'~Lemon Blueberry Pie~', q'~Tangy lemon curd and juicy blueberries nestled in a flaky crust, topped with a sweet crumble and lemon zest.~');
create_item(c, q'~Lemon Chess Pie~', q'~A Southern favorite featuring a tangy lemon custard filling in a flaky shell, baked until set and finished with a dusting of powdered sugar.~');
create_item(c, q'~Lemon Coconut Biscotti~', q'~Crunchy biscotti infused with fresh lemon zest and sweet coconut flakes, finished with a light lemon glaze.~');
create_item(c, q'~Lemon Coconut Cookie~', q'~Tender cookies infused with fresh lemon zest and sweet coconut flakes, finished with a light lemon glaze.~');
create_item(c, q'~Lemon Coconut Layer Cake~', q'~Lemon cake filled with coconut cream and lemon curd, topped with toasted coconut and lemon zest.~');
create_item(c, q'~Lemon Coconut Pie~', q'~Tangy lemon custard and creamy coconut filling in a crisp shell, topped with toasted coconut and lemon zest.~');
create_item(c, q'~Lemon Drizzle Cake~', q'~Moist lemon cake soaked with tangy lemon syrup and topped with a zesty lemon glaze, creating a bright, citrusy flavor that awakens the palate.~');
create_item(c, q'~Lemon Lavender Biscotti~', q'~Crunchy biscotti infused with fresh lemon zest and fragrant lavender, offering a floral aroma and a subtly sweet flavor.~');
create_item(c, q'~Lemon Lavender Cookie~', q'~Delicate cookies infused with fresh lemon zest and fragrant lavender, offering a floral aroma and a subtly sweet flavor.~');
create_item(c, q'~Lemon Meringue Pie~', q'~A tart and tangy lemon curd filling in a flaky crust, topped with a billowy, golden-brown meringue. The perfect balance of sweet and sour flavors.~');
create_item(c, q'~Lemon Pistachio Biscotti~', q'~Crunchy biscotti bursting with fresh lemon zest and roasted pistachios, perfect for dipping in coffee or tea.~');
create_item(c, q'~Lemon Pistachio Cake~', q'~Lemon cake filled with pistachio cream and lemon curd, topped with chopped pistachios and lemon zest.~');
create_item(c, q'~Lemon Pistachio Cookie~', q'~Tender cookies bursting with fresh lemon zest and crunchy pistachios, finished with a sweet lemon glaze.~');
create_item(c, q'~Lemon Poppy Seed Cake~', q'~Lemon cake studded with crunchy poppy seeds, layered with lemon cream and finished with a sweet lemon glaze.~');
create_item(c, q'~Lemon Poppy Seed Cookie~', q'~Bright and zesty cookies bursting with fresh lemon zest and crunchy poppy seeds, finished with a sweet lemon glaze for a refreshing twist.~');
create_item(c, q'~Lemon Raspberry Biscotti~', q'~Crunchy biscotti filled with sweet raspberry pieces and fresh lemon zest, offering a vibrant and refreshing treat.~');
create_item(c, q'~Lemon Raspberry Cookie~', q'~Tender cookies bursting with fresh lemon zest and sweet raspberry pieces, finished with a light lemon glaze.~');
create_item(c, q'~Lemon Raspberry Layer Cake~', q'~Lemon cake layered with raspberry preserves and lemon cream, finished with fresh raspberries and lemon zest.~');
create_item(c, q'~Lemon Raspberry Mousse Cake~', q'~Lemon cake layered with raspberry mousse and lemon cream, finished with fresh raspberries and lemon zest.~');
create_item(c, q'~Lemon Raspberry Pie~', q'~Tangy lemon curd and sweet raspberries nestled in a crisp shell, finished with whipped cream and lemon zest.~');
create_item(c, q'~Lemon Ricotta Cake~', q'~Tender ricotta cake infused with lemon zest, layered with lemon cream and finished with candied lemon slices.~');
create_item(c, q'~Lemon Ricotta Cheesecake~', q'~A light and tangy cheesecake made with ricotta cheese and fresh lemon zest, baked on a buttery shortbread crust and dusted with powdered sugar.~');
create_item(c, q'~Lemon Ricotta Cookie~', q'~Soft, cake-like cookies made with creamy ricotta cheese and bright lemon zest, finished with a sweet lemon glaze.~');
create_item(c, q'~Lemon Strawberry Blueberry Cream Pie~', q'~Tangy lemon curd, sweet strawberries, and juicy blueberries atop a smooth vanilla cream in a crisp shell, finished with whipped cream.~');
create_item(c, q'~Lemon Strawberry Cake~', q'~Lemon cake filled with strawberry cream and lemon curd, topped with fresh strawberries and lemon zest.~');
create_item(c, q'~Lemon Strawberry Cream Pie~', q'~Tangy lemon curd and sweet strawberries atop a smooth vanilla cream in a graham cracker crust, finished with whipped cream.~');
create_item(c, q'~Lemon Strawberry Pie~', q'~Tangy lemon curd and sweet strawberries nestled in a crisp shell, finished with whipped cream and lemon zest.~');
create_item(c, q'~Lemon Strawberry Pistachio Cream Pie~', q'~Tangy lemon curd, sweet strawberries, and crunchy pistachios atop a smooth vanilla cream in a crisp shell, finished with whipped cream.~');
create_item(c, q'~Lemon Sugar Cookie~', q'~Tender sugar cookies infused with fresh lemon zest, finished with a sweet lemon glaze for a refreshing twist.~');
create_item(c, q'~Lemon Tart~', q'~A crisp, buttery pastry shell filled with tangy, silky lemon curd. The tart is baked until set and often finished with a dusting of powdered sugar or a swirl of whipped cream for a refreshing, zesty dessert.~');
create_item(c, q'~Lemon Thyme Cake~', q'~Lemon cake infused with fresh thyme, layered with lemon cream and finished with candied lemon slices and thyme sprigs.~');
create_item(c, q'~Lemon Thyme Cookie~', q'~Delicate cookies infused with fresh lemon zest and aromatic thyme, offering a unique citrus-herb flavor profile.~');
create_item(c, q'~Lemon White Chocolate Cookie~', q'~Soft cookies infused with fresh lemon zest and packed with creamy white chocolate chips, finished with a sweet lemon glaze.~');
create_item(c, q'~Lime Coconut Cake~', q'~Zesty lime cake filled with coconut cream and lime curd, topped with toasted coconut and lime zest.~');
create_item(c, q'~Lime Coconut Macaroon~', q'~Chewy coconut macaroons infused with fresh lime zest, finished with a light lime glaze for a tropical, tangy twist.~');
create_item(c, q'~Lime Coconut Pie~', q'~Zesty lime custard and creamy coconut filling in a crisp shell, topped with toasted coconut and lime zest.~');
create_item(c, q'~Lime Raspberry Cake~', q'~Lime cake layered with raspberry preserves and lime cream, topped with fresh raspberries and lime zest.~');
create_item(c, q'~Lime Raspberry Pie~', q'~Tangy lime curd and sweet raspberries nestled in a crisp shell, finished with whipped cream and lime zest.~');
create_item(c, q'~Linzer Torte~', q'~An Austrian tart made with a buttery, nutty dough (often almonds or hazelnuts) and filled with raspberry or red currant jam, topped with a lattice crust.~');
create_item(c, q'~Maamoul~', q'~Shortbread-like cookies from the Middle East, filled with dates, nuts, or figs, and molded into decorative shapes. Delicate, buttery, and lightly sweet.~');
create_item(c, q'~Madeleine~', q'~A classic French sponge cake baked in a distinctive shell shape, with a light, buttery texture and a hint of lemon or vanilla. Perfect for dipping in tea.~');
create_item(c, q'~Mango Cheesecake~', q'~Tropical mango puree blended into creamy cheesecake, layered on a coconut-graham crust and topped with a glossy mango glaze and fresh mango slices.~');
create_item(c, q'~Mango Coconut Cake~', q'~Tropical mango cake filled with coconut cream and mango puree, topped with fresh mango slices and toasted coconut.~');
create_item(c, q'~Mango Passionfruit Cake~', q'~Mango cake layered with passionfruit curd and mango cream, topped with fresh mango and passionfruit seeds.~');
create_item(c, q'~Mango Sticky Rice~', q'~A popular Thai dessert featuring sweet, glutinous rice cooked in coconut milk, served with ripe mango slices and drizzled with more coconut cream. Finished with a sprinkle of sesame seeds or mung beans.~');
create_item(c, q'~Maple Pecan Chocolate Pie~', q'~Toasted pecans and chocolate chunks in a silky maple custard, baked in a flaky shell for a decadent treat.~');
create_item(c, q'~Maple Pecan Pie~', q'~Toasted pecans suspended in a silky maple custard, baked in a flaky crust. The deep maple flavor and crunchy nuts make this a decadent Southern classic.~');
create_item(c, q'~Maple Pumpkin Chocolate Pecan Pie~', q'~Pumpkin custard sweetened with maple syrup and layered with chocolate and toasted pecans in a buttery shell.~');
create_item(c, q'~Maple Pumpkin Chocolate Pie~', q'~Pumpkin custard sweetened with maple syrup and layered with chocolate in a buttery shell, topped with whipped cream.~');
create_item(c, q'~Maple Pumpkin Pecan Pie~', q'~Pumpkin custard sweetened with maple syrup and topped with toasted pecans, baked in a flaky shell.~');
create_item(c, q'~Maple Pumpkin Pie~', q'~Pumpkin custard sweetened with pure maple syrup, baked in a crisp shell and topped with maple whipped cream.~');
create_item(c, q'~Maple Walnut Cake~', q'~Soft maple-flavored cake filled with maple buttercream and studded with toasted walnuts, delivering a warm, comforting sweetness.~');
create_item(c, q'~Maple Walnut Cookie~', q'~Chewy cookies flavored with pure maple syrup and studded with toasted walnuts, delivering a warm, comforting sweetness and a satisfying crunch.~');
create_item(c, q'~Maple Walnut Pie~', q'~Toasted walnuts in a silky maple custard, baked in a flaky crust and finished with a drizzle of maple syrup.~');
create_item(c, q'~Maple Walnut Pumpkin Pie~', q'~Pumpkin custard sweetened with maple syrup and studded with toasted walnuts, baked in a buttery shell.~');
create_item(c, q'~Matcha Green Tea Cake~', q'~Vibrant matcha sponge cake layered with matcha cream and white chocolate ganache, finished with a dusting of matcha powder.~');
create_item(c, q'~Matcha Green Tea Cheesecake~', q'~A Japanese-inspired cheesecake infused with earthy matcha green tea powder, creating a delicate flavor and a beautiful green hue, set on a crisp cookie crust.~');
create_item(c, q'~Matcha White Chocolate Cookie~', q'~Chewy cookies infused with earthy matcha green tea and studded with creamy white chocolate chips, creating a vibrant and unique treat.~');
create_item(c, q'~Meyer Lemon Cheesecake~', q'~A bright and tangy cheesecake made with sweet Meyer lemon juice and zest, baked on a vanilla wafer crust and topped with candied lemon slices.~');
create_item(c, q'~Mississippi Mud Pie~', q'~A rich chocolate pie with a crumbly cookie crust, gooey chocolate filling, and a layer of whipped cream or marshmallow topping. Named for its dense, "muddy" appearance.~');
create_item(c, q'~Mixed Berry Pie~', q'~A medley of strawberries, blueberries, raspberries, and blackberries baked in a golden crust, bursting with juicy, sweet-tart flavor.~');
create_item(c, q'~Mocha Cream Pie~', q'~Silky mocha custard in a chocolate cookie crust, topped with espresso whipped cream and chocolate-covered coffee beans.~');
create_item(c, q'~Mocha Espresso Cake~', q'~Chocolate cake infused with espresso, layered with mocha buttercream and finished with chocolate-covered coffee beans for a bold, aromatic dessert.~');
create_item(c, q'~Mocha Hazelnut Cake~', q'~Coffee-infused chocolate cake layered with hazelnut cream and mocha ganache, topped with toasted hazelnuts.~');
create_item(c, q'~Mochi~', q'~A Japanese treat made from glutinous rice pounded into a chewy, elastic dough, then filled with sweet red bean paste, ice cream, or fruit. Soft, stretchy, and subtly sweet.~');
create_item(c, q'~Molasses Spice Cookie~', q'~Dark, chewy cookies with deep molasses flavor and a blend of cinnamon, cloves, and ginger. Their crackled tops and rich aroma evoke holiday nostalgia.~');
create_item(c, q'~Molten Lava Cake~', q'~A decadent individual chocolate cake with a warm, gooey, molten chocolate center that flows out when cut. Served with vanilla ice cream or berries for a dramatic dessert.~');
create_item(c, q'~Mont Blanc~', q'~A French dessert made with sweetened chestnut puree piped over a mound of whipped cream, resembling a snow-capped mountain. Sometimes served on a crisp meringue base.~');
create_item(c, q'~Oatmeal Chocolate Chunk Cookie~', q'~Hearty oatmeal cookies packed with large chocolate chunks, offering a chewy texture and a comforting blend of wholesome oats and rich chocolate.~');
create_item(c, q'~Oatmeal Raisin Cookie~', q'~A hearty cookie made with rolled oats, plump raisins, and a hint of cinnamon. Chewy and wholesome, often enjoyed as a comforting snack.~');
create_item(c, q'~Opera Cake~', q'~A sophisticated French dessert with layers of almond sponge cake soaked in coffee syrup, coffee buttercream, and chocolate ganache, finished with a shiny chocolate glaze.~');
create_item(c, q'~Orange Blossom Cake~', q'~Fragrant orange cake infused with orange blossom water, layered with citrus cream and decorated with candied orange peel.~');
create_item(c, q'~Orange Cardamom Cake~', q'~Fragrant orange cake infused with cardamom, layered with orange cream and finished with candied orange slices.~');
create_item(c, q'~Orange Cardamom Cookie~', q'~Fragrant cookies infused with fresh orange zest and aromatic cardamom, offering a unique citrus-spice flavor profile and a delicate crumb.~');
create_item(c, q'~Orange Cranberry Cake~', q'~Orange cake filled with cranberry compote and orange cream, topped with candied orange slices and sugared cranberries.~');
create_item(c, q'~Oreo Cheesecake~', q'~A cookies-and-cream lover’s dream: smooth cheesecake studded with crushed Oreo cookies, baked on a chocolate cookie crust and topped with whipped cream and more Oreos.~');
create_item(c, q'~Panna Cotta~', q'~Silky Italian dessert made from sweetened cream set with gelatin, served chilled and topped with fresh berries or fruit coulis.~');
create_item(c, q'~Paris-Brest~', q'~A ring-shaped French choux pastry filled with rich praline-flavored cream and topped with toasted almonds and powdered sugar. Created to commemorate a famous bicycle race.~');
create_item(c, q'~Passionfruit Cake~', q'~Light vanilla cake layered with tangy passionfruit curd and cream, finished with a glossy passionfruit glaze.~');
create_item(c, q'~Pastel de Nata~', q'~A Portuguese custard tart with a crisp, flaky pastry shell and a creamy, caramelized egg custard filling. Served warm, dusted with cinnamon and powdered sugar.~');
create_item(c, q'~Pavlova~', q'~A meringue-based dessert with a crisp crust and soft, marshmallow-like center, topped with whipped cream and fresh fruit such as kiwi, strawberries, and passionfruit. Light and elegant.~');
create_item(c, q'~Peach Almond Pie~', q'~Ripe peaches and almond cream baked in a golden crust, finished with toasted almond flakes.~');
create_item(c, q'~Peach Blackberry Pie~', q'~Juicy peaches and blackberries baked together in a golden crust, offering a harmonious blend of sweet and tart flavors.~');
create_item(c, q'~Peach Blueberry Almond Cream Pie~', q'~Juicy peaches, blueberries, and almond cream baked together in a golden crust, finished with toasted almond flakes.~');
create_item(c, q'~Peach Blueberry Almond Pie~', q'~Juicy peaches, blueberries, and almond cream baked together in a golden crust, finished with toasted almond flakes.~');
create_item(c, q'~Peach Blueberry Pie~', q'~Juicy peaches and blueberries baked together in a golden crust, offering a harmonious blend of sweet and tart flavors.~');
create_item(c, q'~Peach Bourbon Pie~', q'~Ripe peaches tossed with brown sugar and a splash of bourbon, baked in a tender crust for a rich, caramelized flavor. Perfect for summer gatherings.~');
create_item(c, q'~Peach Cobbler~', q'~A classic Southern dessert featuring sweet, juicy peaches baked beneath a golden, biscuit-like topping. Served warm, often with a scoop of vanilla ice cream or whipped cream.~');
create_item(c, q'~Peach Melba Cake~', q'~Vanilla sponge cake layered with peach compote and raspberry cream, topped with fresh peach slices and a drizzle of raspberry sauce.~');
create_item(c, q'~Peach Melba Pie~', q'~Juicy peaches and raspberry sauce baked in a flaky crust, finished with a swirl of vanilla cream.~');
create_item(c, q'~Peach Raspberry Almond Pie~', q'~Ripe peaches, tart raspberries, and almond cream baked in a golden crust, finished with toasted almond flakes.~');
create_item(c, q'~Peach Raspberry Blueberry Pie~', q'~Ripe peaches, tart raspberries, and juicy blueberries baked together in a golden crust, offering a vibrant, summery flavor.~');
create_item(c, q'~Peach Raspberry Pie~', q'~Ripe peaches and tart raspberries baked together in a flaky crust, offering a vibrant, summery flavor.~');
create_item(c, q'~Peanut Butter Banana Cookie~', q'~Soft cookies made with creamy peanut butter and ripe bananas, offering a moist texture and a comforting, nostalgic flavor.~');
create_item(c, q'~Peanut Butter Chocolate Chip Biscotti~', q'~Crunchy biscotti packed with creamy peanut butter and melty chocolate chips, delivering a rich, nutty flavor and a decadent texture.~');
create_item(c, q'~Peanut Butter Chocolate Chip Cookie~', q'~Chewy peanut butter cookies packed with melty chocolate chips, delivering a rich, nutty flavor and a decadent texture.~');
create_item(c, q'~Peanut Butter Chocolate Swirl Cookie~', q'~Soft peanut butter cookies marbled with ribbons of chocolate, creating a visually stunning and deliciously balanced treat.~');
create_item(c, q'~Peanut Butter Cookie~', q'~A rich, crumbly cookie with a deep peanut butter flavor, often marked with a crisscross pattern on top. Salty-sweet and satisfying.~');
create_item(c, q'~Peanut Butter Cup Cheesecake~', q'~Rich peanut butter cheesecake loaded with chunks of peanut butter cups, set on a chocolate cookie crust and topped with chocolate ganache and chopped peanuts.~');
create_item(c, q'~Peanut Butter Marshmallow Cookie~', q'~Chewy peanut butter cookies with gooey marshmallow centers, offering a decadent, s’mores-inspired treat.~');
create_item(c, q'~Peanut Butter Oatmeal Cookie~', q'~Chewy cookies combining creamy peanut butter and hearty oats, delivering a wholesome texture and a rich, nutty flavor.~');
create_item(c, q'~Peanut Butter Pie~', q'~A creamy, no-bake pie with a chocolate cookie crust and a rich peanut butter filling, topped with whipped cream and chocolate shavings for a sweet-salty treat.~');
create_item(c, q'~Peanut Butter Pretzel Cookie~', q'~Chewy peanut butter cookies loaded with crunchy pretzel pieces, offering a sweet-salty flavor explosion.~');
create_item(c, q'~Pear Almond Cake~', q'~Almond cake layered with poached pear slices and almond cream, topped with toasted almonds and pear glaze.~');
create_item(c, q'~Pear Almond Pie~', q'~Tender pears and almond frangipane baked in a buttery shell, finished with sliced almonds and powdered sugar.~');
create_item(c, q'~Pear Ginger Cake~', q'~Spiced ginger cake layered with pear compote and ginger cream, topped with poached pear slices and candied ginger.~');
create_item(c, q'~Pear Ginger Pie~', q'~Tender pears tossed with fresh ginger and brown sugar, baked in a buttery crust for a fragrant, subtly spicy dessert.~');
create_item(c, q'~Pecan Pie~', q'~A Southern favorite with a flaky pie crust filled with a gooey, caramel-like mixture of eggs, butter, and brown sugar, generously studded with toasted pecan halves. Sweet, nutty, and rich.~');
create_item(c, q'~Pecan Sandie~', q'~Tender shortbread cookies loaded with toasted pecans, delivering a buttery, crumbly texture and a nutty, satisfying flavor.~');
create_item(c, q'~Pineapple Coconut Cake~', q'~Tropical pineapple cake filled with coconut cream and pineapple chunks, topped with toasted coconut and pineapple flowers.~');
create_item(c, q'~Pineapple Mango Pie~', q'~Tropical pineapple and mango chunks in a sweet filling, baked in a crisp crust and finished with a sprinkle of toasted coconut.~');
create_item(c, q'~Pineapple Upside-Down Cake~', q'~A moist vanilla cake baked with caramelized pineapple rings and maraschino cherries on the bottom, then inverted to reveal a glossy, fruity topping.~');
create_item(c, q'~Pistachio Cheesecake~', q'~Creamy cheesecake blended with roasted pistachios, set on a pistachio shortbread crust and topped with whipped cream and chopped pistachios.~');
create_item(c, q'~Pistachio Cranberry Cookie~', q'~Chewy cookies filled with roasted pistachios and tart dried cranberries, delivering a festive blend of flavors and colors.~');
create_item(c, q'~Pistachio Cranberry Sandwich Cookie~', q'~Crisp cookies packed with roasted pistachios and tart dried cranberries, sandwiched with creamy filling for a festive treat.~');
create_item(c, q'~Pistachio Cream Pie~', q'~Smooth pistachio custard in a buttery crust, topped with whipped cream and chopped roasted pistachios.~');
create_item(c, q'~Pistachio Rose Cake~', q'~Delicate pistachio sponge cake layered with rosewater cream and adorned with crushed pistachios and edible rose petals for a floral, nutty finish.~');
create_item(c, q'~Pistachio Rose Cookie~', q'~Delicate cookies flavored with rosewater and studded with roasted pistachios, finished with a light glaze for a floral, nutty treat.~');
create_item(c, q'~Pistachio White Chocolate Cookie~', q'~Soft cookies packed with roasted pistachios and creamy white chocolate chips, delivering a luxurious, nutty flavor.~');
create_item(c, q'~Plum Cardamom Pie~', q'~Juicy plums and aromatic cardamom combine in a golden pastry shell, offering a sophisticated blend of sweet and spice.~');
create_item(c, q'~Profiteroles~', q'~Small, round choux pastry puffs filled with sweet whipped cream, custard, or ice cream, and drizzled with warm chocolate sauce. Often served stacked as a dramatic dessert centerpiece.~');
create_item(c, q'~Pumpkin Chai Pie~', q'~Creamy pumpkin filling infused with chai spices, baked in a flaky crust and topped with cinnamon whipped cream for a warming autumn treat.~');
create_item(c, q'~Pumpkin Cheesecake~', q'~A seasonal favorite with spiced pumpkin puree blended into creamy cheesecake, baked on a gingersnap crust and topped with cinnamon whipped cream.~');
create_item(c, q'~Pumpkin Cheesecake Pie~', q'~Pumpkin custard layered over creamy cheesecake in a graham cracker crust, topped with cinnamon whipped cream.~');
create_item(c, q'~Pumpkin Chocolate Chip Cake~', q'~Pumpkin cake studded with chocolate chips, layered with spiced cream cheese frosting and finished with chocolate drizzle.~');
create_item(c, q'~Pumpkin Chocolate Chip Cookie~', q'~Soft pumpkin cookies studded with melty chocolate chips, offering a moist texture and a blend of autumn spices.~');
create_item(c, q'~Pumpkin Chocolate Chip Pie~', q'~Pumpkin custard studded with chocolate chips, baked in a buttery shell and topped with whipped cream.~');
create_item(c, q'~Pumpkin Chocolate Pecan Pie~', q'~Pumpkin custard layered with chocolate and toasted pecans in a buttery shell, topped with whipped cream.~');
create_item(c, q'~Pumpkin Cranberry Cake~', q'~Pumpkin cake filled with cranberry compote and spiced cream cheese frosting, topped with sugared cranberries.~');
create_item(c, q'~Pumpkin Cranberry Cookie~', q'~Soft pumpkin cookies filled with tart dried cranberries, offering a moist texture and a blend of autumn flavors.~');
create_item(c, q'~Pumpkin Cranberry Mousse Cake~', q'~Pumpkin cake layered with cranberry mousse and spiced cream cheese frosting, topped with sugared cranberries.~');
create_item(c, q'~Pumpkin Cranberry Oatmeal Cookie~', q'~Hearty oatmeal cookies infused with pumpkin puree and filled with tart dried cranberries, offering a chewy texture and a blend of autumn flavors.~');
create_item(c, q'~Pumpkin Cranberry Pie~', q'~Pumpkin custard and tart cranberries baked together in a buttery shell, topped with whipped cream.~');
create_item(c, q'~Pumpkin Maple Cake~', q'~Pumpkin cake layered with maple cream cheese frosting and topped with candied pecans and a maple drizzle.~');
create_item(c, q'~Pumpkin Maple Layer Cake~', q'~Pumpkin cake layered with maple cream cheese frosting and topped with candied pecans and a maple drizzle.~');
create_item(c, q'~Pumpkin Maple Pecan Pie~', q'~Pumpkin custard sweetened with maple syrup and topped with toasted pecans, baked in a flaky shell.~');
create_item(c, q'~Pumpkin Maple Pie~', q'~Pumpkin custard sweetened with pure maple syrup, baked in a buttery shell and topped with maple whipped cream.~');
create_item(c, q'~Pumpkin Maple Walnut Chocolate Pie~', q'~Pumpkin custard sweetened with maple syrup and layered with chocolate and toasted walnuts in a buttery shell.~');
create_item(c, q'~Pumpkin Maple Walnut Pecan Chocolate Pie~', q'~Pumpkin custard sweetened with maple syrup and layered with chocolate, toasted walnuts, and pecans in a buttery shell.~');
create_item(c, q'~Pumpkin Maple Walnut Pecan Pie~', q'~Pumpkin custard sweetened with maple syrup and studded with toasted walnuts and pecans, baked in a buttery shell.~');
create_item(c, q'~Pumpkin Maple Walnut Pie~', q'~Pumpkin custard sweetened with maple syrup and studded with toasted walnuts, baked in a buttery shell.~');
create_item(c, q'~Pumpkin Oatmeal Cookie~', q'~Hearty oatmeal cookies infused with pumpkin puree and autumn spices, offering a chewy texture and a warm, comforting flavor.~');
create_item(c, q'~Pumpkin Pecan Biscotti~', q'~Crunchy biscotti infused with pumpkin puree and loaded with toasted pecans, offering a blend of autumn spices and a satisfying crunch.~');
create_item(c, q'~Pumpkin Pecan Cake~', q'~Pumpkin cake filled with pecan cream and spiced cream cheese frosting, topped with toasted pecans.~');
create_item(c, q'~Pumpkin Pecan Cookie~', q'~Soft pumpkin cookies loaded with toasted pecans, offering a moist texture and a blend of autumn spices.~');
create_item(c, q'~Pumpkin Pecan Pie~', q'~Creamy pumpkin filling topped with a layer of toasted pecans, baked in a buttery shell for a festive twist.~');
create_item(c, q'~Pumpkin Pie~', q'~A holiday staple with a flaky crust and a creamy, spiced pumpkin filling made with cinnamon, nutmeg, and cloves. Baked until set and served with a dollop of whipped cream.~');
create_item(c, q'~Pumpkin Roll~', q'~A spiced pumpkin cake baked in a thin sheet, spread with sweet cream cheese filling, and rolled into a spiral. Sliced to reveal a beautiful swirl pattern.~');
create_item(c, q'~Pumpkin Spice Cake~', q'~Moist pumpkin cake spiced with cinnamon and nutmeg, layered with cream cheese frosting and topped with candied pecans.~');
create_item(c, q'~Pumpkin Spice Cookie~', q'~Soft cookies infused with pumpkin puree and autumn spices, topped with a cinnamon cream cheese drizzle. Perfect for cozy fall afternoons.~');
create_item(c, q'~Pumpkin Walnut Cake~', q'~Pumpkin cake filled with walnut cream and spiced cream cheese frosting, topped with toasted walnuts.~');
create_item(c, q'~Pumpkin Walnut Mousse Cake~', q'~Pumpkin cake layered with walnut mousse and spiced cream cheese frosting, topped with toasted walnuts.~');
create_item(c, q'~Pumpkin Walnut Pie~', q'~Creamy pumpkin filling and toasted walnuts baked in a buttery shell, topped with cinnamon whipped cream.~');
create_item(c, q'~Pumpkin White Chocolate Chip Biscotti~', q'~Crunchy biscotti infused with pumpkin puree and studded with creamy white chocolate chips, offering a blend of autumn spices and a satisfying crunch.~');
create_item(c, q'~Pumpkin White Chocolate Chip Cookie~', q'~Soft pumpkin cookies studded with creamy white chocolate chips, offering a moist texture and a blend of autumn spices.~');
create_item(c, q'~Qatayef~', q'~A stuffed pancake dessert popular during Ramadan, filled with sweet cheese or nuts, folded and fried or baked, then drizzled with syrup.~');
create_item(c, q'~Rasgulla~', q'~Spongy, soft cheese balls made from chenna (Indian cottage cheese), cooked in a light sugar syrup. A popular Bengali dessert, served chilled and syrupy.~');
create_item(c, q'~Raspberry Coconut Cake~', q'~Coconut cake filled with raspberry preserves and coconut cream, topped with fresh raspberries and toasted coconut.~');
create_item(c, q'~Raspberry Lemon Cake~', q'~Lemon cake layered with raspberry preserves and lemon cream, finished with fresh raspberries and lemon zest.~');
create_item(c, q'~Raspberry Lemon Mousse Cake~', q'~Lemon cake layered with raspberry mousse and lemon cream, finished with fresh raspberries and lemon zest.~');
create_item(c, q'~Raspberry Lemon Pie~', q'~Bright raspberries and zesty lemon curd combine in a crisp pastry shell, offering a sweet-tart sensation with every forkful.~');
create_item(c, q'~Raspberry Lemonade Cake~', q'~Lemon cake layered with raspberry compote and lemon cream, finished with a swirl of raspberry glaze for a sweet-tart sensation.~');
create_item(c, q'~Raspberry Pistachio Cake~', q'~Pistachio cake filled with raspberry preserves and pistachio cream, topped with fresh raspberries and chopped pistachios.~');
create_item(c, q'~Raspberry Thumbprint Cookie~', q'~Tender butter cookies with a center of vibrant raspberry jam, finished with a dusting of powdered sugar for a classic, elegant look.~');
create_item(c, q'~Raspberry White Chocolate Cake~', q'~Vanilla cake layered with raspberry preserves and white chocolate cream, finished with fresh raspberries and white chocolate curls.~');
create_item(c, q'~Raspberry White Chocolate Cheesecake~', q'~Silky white chocolate cheesecake swirled with tart raspberry puree, baked on a chocolate cookie crust and garnished with fresh raspberries.~');
create_item(c, q'~Raspberry White Chocolate Chip Cookie~', q'~Soft cookies filled with sweet raspberry pieces and creamy white chocolate chips, creating a vibrant and indulgent treat.~');
create_item(c, q'~Raspberry White Chocolate Pie~', q'~Sweet raspberries and creamy white chocolate mousse in a crisp shell, finished with fresh berries and white chocolate curls.~');
create_item(c, q'~Red Currant Cake~', q'~Light sponge cake layered with tangy red currant jam and vanilla cream, topped with a cascade of fresh red currants.~');
create_item(c, q'~Red Velvet Cake~', q'~A striking red cocoa cake with a tender crumb, layered with tangy cream cheese frosting. Moist, slightly chocolatey, and visually stunning.~');
create_item(c, q'~Red Velvet Cheesecake~', q'~A striking red velvet cake base topped with a layer of classic cheesecake, finished with cream cheese frosting and white chocolate curls.~');
create_item(c, q'~Rhubarb Vanilla Cake~', q'~Vanilla cake layered with tangy rhubarb compote and vanilla cream, topped with roasted rhubarb and a vanilla glaze.~');
create_item(c, q'~Rice Pudding~', q'~A comforting dessert made by simmering rice in soymilk and sugar until creamy, then flavored with vanilla, cinnamon, and sometimes raisins. Served warm or chilled, often sprinkled with ground cinnamon.~');
create_item(c, q'~Rocky Road~', q'~A chocolate confection loaded with marshmallows, roasted nuts, and sometimes dried fruit, creating a chewy, crunchy, and sweet treat. Served as bars or ice cream.~');
create_item(c, q'~Rum Baba~', q'~A small yeast cake soaked in rum syrup, often filled with whipped cream or pastry cream. Moist, boozy, and served as an elegant dessert.~');
create_item(c, q'~Rum Raisin Cake~', q'~Spiced cake soaked with rum and studded with plump raisins, layered with rum buttercream and topped with golden raisins.~');
create_item(c, q'~Sacher Torte~', q'~A famous Austrian chocolate cake with layers of dense chocolate sponge, apricot jam, and a smooth dark chocolate glaze. Served with unsweetened whipped cream.~');
create_item(c, q'~Sago Pudding~', q'~A creamy pudding made from translucent tapioca pearls simmered in coconut milk and sweetened with sugar. Served chilled, sometimes with fruit or syrup.~');
create_item(c, q'~Salted Caramel Apple Pie~', q'~Tender apples layered with gooey salted caramel, baked in a buttery crust and finished with a sprinkle of flaky sea salt.~');
create_item(c, q'~Salted Caramel Cake~', q'~Buttery cake layered with salted caramel sauce and caramel buttercream, topped with a sprinkle of flaky sea salt for a sweet-salty delight.~');
create_item(c, q'~Salted Caramel Cheesecake~', q'~Ultra-creamy cheesecake layered with luscious salted caramel sauce, set on a buttery cookie crust and finished with a sprinkle of flaky sea salt.~');
create_item(c, q'~Salted Caramel Cookie~', q'~Buttery cookies filled with gooey caramel and finished with a sprinkle of flaky sea salt. The sweet-salty combination is irresistible and melts in your mouth.~');
create_item(c, q'~Semifreddo~', q'~An Italian "half-frozen" dessert with a mousse-like texture, made from whipped cream, eggs, and sugar, often flavored with chocolate, fruit, or nuts. Served sliced, soft, and creamy.~');
create_item(c, q'~Sfogliatella~', q'~A shell-shaped Italian pastry with crisp, flaky layers, filled with a sweet ricotta and semolina mixture, often flavored with candied citrus and cinnamon.~');
create_item(c, q'~Shoofly Pie~', q'~A Pennsylvania Dutch pie with a molasses-based filling, topped with a crumbly streusel. The sweet, sticky filling contrasts with the crisp crust and crumb topping.~');
create_item(c, q'~Smore~', q'~A campfire favorite made by sandwiching toasted marshmallow and a square of chocolate between two graham crackers. Gooey, melty, and nostalgic.~');
create_item(c, q'~Snickerdoodle~', q'~A soft, chewy cookie rolled in cinnamon sugar before baking, giving it a crackled surface and a warm, spicy flavor. A nostalgic favorite.~');
create_item(c, q'~Snickers Cookie~', q'~Chewy cookies packed with chopped Snickers bars, caramel, peanuts, and chocolate, creating a decadent, candy-inspired treat.~');
create_item(c, q'~Spiced Apple Oatmeal Cookie~', q'~Hearty oatmeal cookies with bits of dried apple and a blend of cinnamon and nutmeg, delivering a comforting, autumn-inspired flavor.~');
create_item(c, q'~Spiced Chai Cake~', q'~Soft cake infused with chai spices like cinnamon, cardamom, and ginger, layered with spiced cream cheese frosting and dusted with cinnamon.~');
create_item(c, q'~Spiced Plum Cake~', q'~Spiced cake layered with plum compote and cinnamon cream, topped with roasted plums and a cinnamon glaze.~');
create_item(c, q'~Sticky Rice Cake~', q'~A sweet Asian dessert made from glutinous rice, sometimes filled with sweet bean paste or nuts, and steamed or baked until chewy and sticky.~');
create_item(c, q'~Sticky Toffee Pudding~', q'~A moist British sponge cake made with finely chopped dates, drenched in a warm, buttery toffee sauce. Served hot, often with vanilla ice cream or custard for a comforting finish.~');
create_item(c, q'~Strawberry Almond Cake~', q'~Almond cake filled with strawberry cream and fresh strawberries, topped with sliced almonds and strawberry glaze.~');
create_item(c, q'~Strawberry Champagne Cake~', q'~Champagne-infused sponge cake layered with strawberry cream and fresh strawberries, finished with a sparkling glaze.~');
create_item(c, q'~Strawberry Cream Cheese Pie~', q'~Fresh strawberries atop a tangy cream cheese layer in a graham cracker crust, finished with a glossy strawberry glaze.~');
create_item(c, q'~Strawberry Cream Pie~', q'~Fresh strawberries atop a smooth vanilla cream in a graham cracker crust, finished with whipped cream and strawberry glaze.~');
create_item(c, q'~Strawberry Lemon Blueberry Pie~', q'~Sweet strawberries, tangy lemon curd, and juicy blueberries nestled in a crisp shell, finished with whipped cream.~');
create_item(c, q'~Strawberry Lemon Cake~', q'~Lemon cake layered with strawberry compote and lemon cream, finished with fresh strawberries and lemon zest.~');
create_item(c, q'~Strawberry Lemon Cream Pie~', q'~Fresh strawberries atop a tangy lemon cream in a graham cracker crust, finished with whipped cream and lemon zest.~');
create_item(c, q'~Strawberry Lemon Mousse Cake~', q'~Lemon cake layered with strawberry mousse and lemon cream, finished with fresh strawberries and lemon zest.~');
create_item(c, q'~Strawberry Lemon Pistachio Pie~', q'~Sweet strawberries, tangy lemon curd, and crunchy pistachios layered in a crisp shell, finished with whipped cream.~');
create_item(c, q'~Strawberry Lemonade Pie~', q'~Sweet strawberries and tangy lemon curd in a graham cracker crust, topped with whipped cream and lemon zest.~');
create_item(c, q'~Strawberry Mango Cake~', q'~Mango cake layered with strawberry cream and fresh mango, finished with strawberry glaze and mango slices.~');
create_item(c, q'~Strawberry Pistachio Cake~', q'~Pistachio cake layered with strawberry compote and pistachio cream, topped with fresh strawberries and chopped pistachios.~');
create_item(c, q'~Strawberry Pistachio Mousse Cake~', q'~Pistachio cake layered with strawberry mousse and pistachio cream, topped with fresh strawberries and chopped pistachios.~');
create_item(c, q'~Strawberry Pistachio Pie~', q'~Sweet strawberries and crunchy pistachios layered in a crisp shell, finished with whipped cream and chopped pistachios.~');
create_item(c, q'~Strawberry Rhubarb Crumble Pie~', q'~Sweet strawberries and tart rhubarb in a flaky shell, topped with a buttery oat crumble for added texture.~');
create_item(c, q'~Strawberry Rhubarb Pie~', q'~Sweet strawberries and tangy rhubarb meld together in a vibrant filling, wrapped in a golden crust. The balance of flavors creates a refreshing, nostalgic treat.~');
create_item(c, q'~Strawberry Shortcake~', q'~Light sponge cake layered with sweet macerated strawberries and clouds of whipped cream, offering a refreshing balance of fruit and cream in every slice.~');
create_item(c, q'~Strawberry Shortcake Cookie~', q'~Soft cookies bursting with real strawberry pieces and creamy white chocolate, reminiscent of classic strawberry shortcake in every bite.~');
create_item(c, q'~Strawberry Swirl Cheesecake~', q'~Creamy vanilla cheesecake with ribbons of sweet strawberry puree swirled throughout, baked on a crisp graham cracker crust and topped with fresh strawberries.~');
create_item(c, q'~Sugar Cookie~', q'~A sweet, buttery cookie with a tender crumb, perfect for decorating with icing or sprinkles. Simple yet delicious, popular for holidays and celebrations.~');
create_item(c, q'~Sweet Potato Pie~', q'~Creamy sweet potato filling spiced with cinnamon and nutmeg, baked in a flaky crust and topped with whipped cream.~');
create_item(c, q'~S’mores Cheesecake~', q'~A campfire-inspired cheesecake with a graham cracker crust, chocolate cheesecake filling, and a toasted marshmallow topping.~');
create_item(c, q'~S’mores Cookie~', q'~Graham cracker cookies loaded with gooey marshmallows and melted chocolate chunks, capturing the essence of campfire s’mores in every bite.~');
create_item(c, q'~Taiyaki~', q'~A fish-shaped Japanese cake with a crisp exterior and a sweet filling, typically red bean paste, custard, or chocolate. Popular as a street food snack.~');
create_item(c, q'~Tarte Tatin~', q'~A French upside-down tart made by caramelizing apples in butter and sugar, then baking with a pastry crust. Inverted before serving to reveal glossy, tender fruit.~');
create_item(c, q'~Tartufo~', q'~An Italian frozen dessert consisting of a ball of gelato with a hidden center of fruit or syrup, coated in a chocolate shell and sometimes rolled in cocoa or nuts.~');
create_item(c, q'~Tiramisu~', q'~A decadent Italian dessert made by layering espresso-soaked ladyfinger biscuits with a rich mascarpone cream, dusted with cocoa powder. Chilled to perfection, offering a harmonious blend of coffee and creamy sweetness.~');
create_item(c, q'~Tiramisu Layer Cake~', q'~Coffee-soaked sponge cake layered with mascarpone cream and dusted with cocoa powder, capturing the essence of classic tiramisu in cake form.~');
create_item(c, q'~Toffee Chip Cookie~', q'~Buttery cookies loaded with crunchy toffee bits and chocolate chips, delivering a sweet, caramelized flavor and a delightful texture.~');
create_item(c, q'~Tres Leches Cake~', q'~A light sponge cake soaked in a mixture of three milks—evaporated, condensed, and heavy cream—resulting in a moist, sweet, and creamy dessert. Topped with whipped cream and fruit.~');
create_item(c, q'~Triple Ginger Cookie~', q'~Spicy cookies made with fresh, ground, and crystallized ginger, creating layers of warmth and flavor. Their chewy texture and aromatic spice are unforgettable.~');
create_item(c, q'~Tteok~', q'~A Korean rice cake dessert made from steamed glutinous rice flour, often filled with sweetened red bean paste or coated in powdered beans. Chewy and subtly sweet.~');
create_item(c, q'~Tufahije~', q'~A Bosnian dessert of poached apples stuffed with walnuts and sugar, simmered in syrup and often topped with whipped cream. Served chilled for a refreshing treat.~');
create_item(c, q'~Turtle Cheesecake~', q'~A decadent treat with a chocolate cookie crust, creamy cheesecake, and layers of gooey caramel, toasted pecans, and rich chocolate ganache.~');
create_item(c, q'~Vanilla Bean Layer Cake~', q'~Tender vanilla sponge cake infused with real vanilla bean, stacked with creamy vanilla buttercream and decorated with delicate sugar pearls for an elegant finish.~');
create_item(c, q'~Vanilla Blueberry Cake~', q'~Vanilla cake filled with blueberry compote and vanilla cream, topped with fresh blueberries and vanilla glaze.~');
create_item(c, q'~Vanilla Hazelnut Cake~', q'~Vanilla cake layered with hazelnut cream and vanilla buttercream, finished with toasted hazelnuts and vanilla glaze.~');
create_item(c, q'~Vanilla Mango Cake~', q'~Vanilla cake layered with mango cream and fresh mango, finished with vanilla buttercream and mango glaze.~');
create_item(c, q'~Vanilla Pistachio Cake~', q'~Vanilla cake layered with pistachio cream and vanilla buttercream, finished with chopped pistachios and vanilla glaze.~');
create_item(c, q'~Vanilla Strawberry Cake~', q'~Vanilla cake layered with strawberry cream and fresh strawberries, finished with vanilla buttercream and strawberry glaze.~');
create_item(c, q'~Walnut Coffee Cake~', q'~Coffee-flavored cake layered with walnut cream and coffee buttercream, finished with toasted walnuts and a dusting of cocoa.~');
create_item(c, q'~White Chocolate Cranberry Cookie~', q'~Soft cookies loaded with creamy white chocolate chips and tart dried cranberries, creating a festive blend of flavors and colors. Perfect for holiday gatherings.~');
create_item(c, q'~White Chocolate Macadamia Cookie~', q'~Soft cookies packed with creamy white chocolate chips and buttery macadamia nuts, offering a luxurious, tropical flavor.~');
create_item(c, q'~Yokan~', q'~A traditional Japanese dessert made from red bean paste, agar, and sugar, set into a firm, sliceable jelly. Served in neat blocks, subtly sweet and smooth.~');
create_item(c, q'~Zabaglione~', q'~A classic Italian custard dessert made by whisking egg yolks, sugar, and sweet wine (usually Marsala) over gentle heat until light and frothy. Served warm or chilled, sometimes with fruit.~');


    select count(*) into l_count 
    from menu_items
    where category_id = l_categories(c);

    dbms_output.put_line('Created ' || l_count || ' menu items for category: ' || c);    

    commit;


exception
    when others then
        dbms_output.put_line(sqlerrm);
end;
/


    

