create table if not exists menu_categories(
     category_id integer generated by default as identity primary key,
     category_name varchar2(100 char) not null unique,
     category_description varchar2(500 char) ,
     created date default sysdate not null,
     created_by varchar2(100 char) not null,
     updated date, 
     updated_by varchar2(100 char)
)
/

create table if not exists menu_items(
     item_id integer generated by default as identity primary key,
     item_name varchar2(100) not null unique,
     category_id references menu_categories(category_id),
     item_description varchar2(500),
     embedding vector,
     quantized_embedding vector,
     created date default sysdate not null,
     created_by varchar2(100) not null,
     updated date, 
     updated_by varchar2(100)
)
/

