create table if not exists menu_categories(
     category_id integer 
        generated by default as identity 
        constraint menu_categories_pk primary key
    , category_name varchar2(100 char) 
        constraint menu_categories_nn_category_name not null 
        constraint menu_categories_u_category_name unique
    , category_description varchar2(1000 char)
    , created_by varchar2(100 char) default user
    , created_date date default sysdate
    , updated_by varchar2(100 char)
    , updated_date date
)
/
