create table if not exists menu_items(
    item_id integer 
        generated by default as identity 
        constraint menu_items_pk primary key
    , item_name varchar2(100 char) 
        constraint menu_items_nn_item_name not null 
        constraint menu_items_u_item_name unique
    , category_id 
        constraint menu_items_fk_menu_categories
        references menu_categories(category_id)
    , item_description varchar2(1000 char)
    , created_by varchar2(100 char) default user
    , created_date date default sysdate
    , updated_by varchar2(100 char)
    , updated_date date
)
/

