
create table accounts (
    account_id number generated by default as identity primary key
    , account_name varchar2(50)
);

create table customers (
    customer_id number generated by default as identity primary key
    , customer_name varchar2(50)
    , account_id number not null references accounts(account_id)
);

create table product_types (
    product_type_id number generated by default as identity primary key
    , product_type_name varchar2(50)
);

create table products (
    product_id number generated by default as identity primary key
    , product_type_id number references product_types(product_type_id)
    , product_name varchar2(50)
    , unit_price number
);

create table orders (
    order_id number generated always as identity primary key
    , customer_id number not null references customers (customer_id)
    , order_date date
);

create table order_details(
    order_detail_id number generated always as identity primary key
    , order_id number not null references orders (order_id)
    , product_id number not null references products (product_id)
    , quantity number not null check (quantity > 0)
);


prompt many orders example tables created